(** This GCode was generated by ReplicatorG Sailfish - 0039 **)
(*  using Skeinforge (50)  *)
(*  for a Dual headed The Replicator  *)
(*  on 2012/12/29 10:38:26 (-0800) *)
(**** start.gcode for The Replicator, dual head ****)
M103 (disable RPM)
M73 P0 (enable build progress)
G21 (set units to mm)
G90 (set positioning to absolute)
G10 P1 X0 Y0 Z0 (Designate T0 Offset)
G10 P2 X33 Y0 Z0 (Designate T1 Offset)
M109 S110 T0 (set HBP temperature)
M104 S190 T0 (set extruder temperature) (temp updated by printOMatic)
G54 (Recall offset cooridinate system)
(**** begin homing ****)
G162 X Y F2500 (home XY axes maximum)
G161 Z F1100 (home Z axis minimum)
G92 Z-5 (set Z to -5)
G1 Z0.0 (move Z to "0")
G161 Z F100 (home Z axis minimum)
M132 X Y Z A B (Recall stored home offsets for XYZAB axis)
(**** end homing ****)
G1 X-110.5 Y-74 Z150 F3300.0 (move to waiting position)
G130 X20 Y20 Z20 A20 B20 (Lower stepper Vrefs while heating)
M6 T0 (wait for toolhead, and HBP to reach temperature)
G130 X127 Y127 Z40 A127 B127 (Set Stepper motor Vref to defaults)
M108 R3.0 T0
G0 X-110.5 Y-74 (Position Nozzle)
G0 Z0.2      (Position Height)
M108 R4.0    (Set Extruder Speed)
M101         (Start Extruder)
G4 P1500     (Create Anchor)
(**** end of start.gcode ****)
(<format> skeinforge gcode </format>)
(<version> 12.03.14 </version>)
(<created> 12.12.29|10:38 </created>)
(<extruderInitialization>)
(<craftTypeName> extrusion </craftTypeName>)
M105
(<decimalPlacesCarried> 3 </decimalPlacesCarried>)
(<layerThickness> 0.25 </layerThickness>)
(<infillWidth> 0.4 </infillWidth>)
(<volumeFraction> 0.82 </volumeFraction>)
(<infillPerimeterOverlap> 0.3 </infillPerimeterOverlap>)
(<sharpestProduct> 0.866 </sharpestProduct>)
(<layerHeight> 0.25 </layerHeight>)
(<threadSequenceString> loops edge infill </threadSequenceString>)
(<maximumZFeedRatePerSecond> 16.0 </maximumZFeedRatePerSecond>)
(<objectFirstLayerFeedRateInfillMultiplier> 0.7 </objectFirstLayerFeedRateInfillMultiplier>)
(<operatingFeedRatePerSecond> 60.0 </operatingFeedRatePerSecond>)
(<objectFirstLayerFlowRateInfillMultiplier> 0.4 </objectFirstLayerFlowRateInfillMultiplier>)
(<operatingFlowRate> 60.0 </operatingFlowRate>)
(<orbitalFeedRatePerSecond> 0.0 </orbitalFeedRatePerSecond>)
(<travelFeedRatePerSecond> 80.0 </travelFeedRatePerSecond>)
(<skirtOutset> 2.6 </skirtOutset>)
(<edgeWidth> 0.4 </edgeWidth>)
(<perimeterWidth> 0.4 </perimeterWidth>)
(<profileName> ABS </profileName>)
(<settings>)
(<setting> alteration Activate_Alteration True </setting>)
(<setting> alteration Name_of_End_File:  </setting>)
(<setting> alteration Name_of_Start_File:  </setting>)
(<setting> alteration Remove_Redundant_Mcode True </setting>)
(<setting> alteration Replace_Variable_with_Setting True </setting>)
(<setting> altshell Activate_Altshell True </setting>)
(<setting> altshell Use_M320/M321 True </setting>)
(<setting> bottom Activate_Bottom True </setting>)
(<setting> bottom Additional_Height_over_Layer_Thickness_(ratio): 1.0 </setting>)
(<setting> bottom Altitude_(mm): 0.2 </setting>)
(<setting> bottom SVG_Viewer: webbrowser </setting>)
(<setting> chamber Activate_Chamber True </setting>)
(<setting> chamber Bed_Temperature_(Celcius): 65.0 </setting>)
(<setting> chamber Bed_Temperature_Begin_Change_Height_(mm): -1.0 </setting>)
(<setting> chamber Bed_Temperature_End_Change_Height_(mm): -1.0 </setting>)
(<setting> chamber Bed_Temperature_End_(Celcius): 20.0 </setting>)
(<setting> chamber Chamber_Temperature_(Celcius): 30.0 </setting>)
(<setting> chamber Holding_Force_(bar): 0.0 </setting>)
(<setting> comb Activate_Comb True </setting>)
(<setting> comb Running_Jump_Space_(mm): 2.0 </setting>)
(<setting> cool Activate_Cool True </setting>)
(<setting> cool Bridge_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Orbit False </setting>)
(<setting> cool Slow_Down True </setting>)
(<setting> cool Maximum_Cool_(Celcius): 1.0 </setting>)
(<setting> cool Minimum_Layer_Time_(seconds): 5.0 </setting>)
(<setting> cool Minimum_Orbital_Radius_(millimeters): 10.0 </setting>)
(<setting> cool Name_of_Cool_End_File: cool_end.gcode </setting>)
(<setting> cool Name_of_Cool_Start_File: cool_start.gcode </setting>)
(<setting> cool Orbital_Outset_(millimeters): 2.0 </setting>)
(<setting> cool Turn_Fan_On_at_Beginning False </setting>)
(<setting> cool Turn_Fan_Off_at_Ending False </setting>)
(<setting> dimension Activate_Dimension True </setting>)
(<setting> dimension Absolute_Extrusion_Distance True </setting>)
(<setting> dimension Relative_Extrusion_Distance False </setting>)
(<setting> dimension Extruder_Retraction_Speed_(mm/s): 20.0 </setting>)
(<setting> dimension Filament_Diameter_(mm): 1.75 </setting>)
(<setting> dimension Filament_Packing_Density_(ratio): 0.9 </setting>)
(<setting> dimension Maximum_E_Value_before_Reset_(float): 91234.0 </setting>)
(<setting> dimension Minimum_Travel_for_Retraction_(millimeters): 1.0 </setting>)
(<setting> dimension Retract_Within_Island False </setting>)
(<setting> dimension Retraction_Distance_(millimeters): 0.0 </setting>)
(<setting> dimension Restart_Extra_Distance_(millimeters): 0.0 </setting>)
(<setting> export Activate_Export True </setting>)
(<setting> export Add_Descriptive_Extension False </setting>)
(<setting> export Add_Export_Suffix False </setting>)
(<setting> export Add_Profile_Extension False </setting>)
(<setting> export Add_Timestamp_Extension False </setting>)
(<setting> export Also_Send_Output_To:  </setting>)
(<setting> export Analyze_Gcode True </setting>)
(<setting> export Do_Not_Delete_Comments True </setting>)
(<setting> export Delete_Crafting_Comments False </setting>)
(<setting> export Delete_All_Comments False </setting>)
(<setting> export Do_Not_Change_Output True </setting>)
(<setting> export binary_16_byte False </setting>)
(<setting> export gcode_step False </setting>)
(<setting> export gcode_time_segment False </setting>)
(<setting> export gcode_small False </setting>)
(<setting> export File_Extension: gcode </setting>)
(<setting> export Name_of_Replace_File: replace.csv </setting>)
(<setting> export Save_Penultimate_Gcode False </setting>)
(<setting> fill Activate_Fill True </setting>)
(<setting> fill Diaphragm_Period_(layers): 100 </setting>)
(<setting> fill Diaphragm_Thickness_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Alternating_Solid_Layer_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Base_(layers): 0 </setting>)
(<setting> fill Extra_Shells_on_Sparse_Layer_(layers): 0 </setting>)
(<setting> fill Grid_Circle_Separation_over_Perimeter_Width_(ratio): 0.2 </setting>)
(<setting> fill Grid_Extra_Overlap_(ratio): 0.1 </setting>)
(<setting> fill Grid_Junction_Separation_Band_Height_(layers): 10 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_End_(ratio): 0.0 </setting>)
(<setting> fill Grid_Junction_Separation_over_Octogon_Radius_At_Middle_(ratio): 0.0 </setting>)
(<setting> fill Infill_Begin_Rotation_(degrees): 45.0 </setting>)
(<setting> fill Infill_Begin_Rotation_Repeat_(layers): 1 </setting>)
(<setting> fill Infill_Odd_Layer_Extra_Rotation_(degrees): 90.0 </setting>)
(<setting> fill Grid_Circular False </setting>)
(<setting> fill Grid_Hexagonal False </setting>)
(<setting> fill Grid_Rectangular False </setting>)
(<setting> fill Line True </setting>)
(<setting> fill Infill_Perimeter_Overlap_(ratio): 0.3 </setting>)
(<setting> fill Infill_Solidity_(ratio): 1.0 </setting>)
(<setting> fill Sharpest_Angle_(degrees): 60.0 </setting>)
(<setting> fill Solid_Surface_Thickness_(layers): 3 </setting>)
(<setting> fill Lower_Left True </setting>)
(<setting> fill Nearest False </setting>)
(<setting> fill Surrounding_Angle_(degrees): 45.0 </setting>)
(<setting> fill Infill_>_Loops_>_Perimeter False </setting>)
(<setting> fill Infill_>_Perimeter_>_Loops False </setting>)
(<setting> fill Loops_>_Infill_>_Perimeter False </setting>)
(<setting> fill Loops_>_Perimeter_>_Infill True </setting>)
(<setting> fill Perimeter_>_Infill_>_Loops False </setting>)
(<setting> fill Perimeter_>_Loops_>_Infill False </setting>)
(<setting> home Activate_Home True </setting>)
(<setting> home Name_of_Home_File: home.gcode </setting>)
(<setting> jitter Activate_Jitter True </setting>)
(<setting> jitter Jitter_Over_Perimeter_Width_(ratio): 2.0 </setting>)
(<setting> raft Activate_Raft True </setting>)
(<setting> raft Add_Raft,_Elevate_Nozzle,_Orbit: False </setting>)
(<setting> raft Base_Feed_Rate_Multiplier_(ratio): 0.75 </setting>)
(<setting> raft Base_Flow_Rate_Multiplier_(ratio): 0.6 </setting>)
(<setting> raft Base_Infill_Density_(ratio): 0.3 </setting>)
(<setting> raft Base_Layer_Thickness_over_Layer_Thickness: 2.2 </setting>)
(<setting> raft Base_Layers_(integer): 0 </setting>)
(<setting> raft Base_Nozzle_Lift_over_Base_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Initial_Circling: False </setting>)
(<setting> raft Infill_Overhang_over_Extrusion_Width_(ratio): 0.1 </setting>)
(<setting> raft Interface_Feed_Rate_Multiplier_(ratio): 1.5 </setting>)
(<setting> raft Interface_Flow_Rate_Multiplier_(ratio): 0.7 </setting>)
(<setting> raft Interface_Infill_Density_(ratio): 0.4 </setting>)
(<setting> raft Interface_Layer_Thickness_over_Layer_Thickness: 1.8 </setting>)
(<setting> raft Interface_Layers_(integer): 0 </setting>)
(<setting> raft Interface_Nozzle_Lift_over_Interface_Layer_Thickness_(ratio): 0.3 </setting>)
(<setting> raft Name_of_Support_End_File: support_end.gcode </setting>)
(<setting> raft Name_of_Support_Start_File: support_start.gcode </setting>)
(<setting> raft Operating_Nozzle_Lift_over_Layer_Thickness_(ratio): 0.0 </setting>)
(<setting> raft Raft_Additional_Margin_over_Length_(%): 2.5 </setting>)
(<setting> raft Raft_Margin_(mm): 2.5 </setting>)
(<setting> raft Support_Cross_Hatch False </setting>)
(<setting> raft Support_Flow_Rate_over_Operating_Flow_Rate_(ratio): 0.7 </setting>)
(<setting> raft Support_Gap_over_Perimeter_Extrusion_Width_(ratio): 0.005 </setting>)
(<setting> raft None False </setting>)
(<setting> raft Empty_Layers_Only False </setting>)
(<setting> raft Everywhere False </setting>)
(<setting> raft Exterior_Only True </setting>)
(<setting> raft Support_Minimum_Angle_(degrees): 45.0 </setting>)
(<setting> skirt Activate_Skirt True </setting>)
(<setting> skirt Convex: True </setting>)
(<setting> skirt Gap_over_Perimeter_Width_(ratio): 6.0 </setting>)
(<setting> skirt Layers_To_(index): 2 </setting>)
(<setting> speed Activate_Speed True </setting>)
(<setting> speed Add_Flow_Rate: True </setting>)
(<setting> speed Bridge_Feed_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Bridge_Flow_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Beginning_(portion): 1.0 </setting>)
(<setting> speed Duty_Cyle_at_Ending_(portion): 0.0 </setting>)
(<setting> speed Feed_Rate_(mm/s): 60.0 </setting>)
(<setting> speed Flow_Rate_Setting_(float): 60.0 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Infill_Multiplier_(ratio): 0.7 </setting>)
(<setting> speed Object_First_Layer_Feed_Rate_Perimeter_Multiplier_(ratio): 0.56 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Infill_Multiplier_(ratio): 0.4 </setting>)
(<setting> speed Object_First_Layer_Flow_Rate_Perimeter_Multiplier_(ratio): 0.8 </setting>)
(<setting> speed Orbital_Feed_Rate_over_Operating_Feed_Rate_(ratio): 0.0 </setting>)
(<setting> speed Maximum_Z_Feed_Rate_(mm/s): 16.0 </setting>)
(<setting> speed Perimeter_Feed_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Perimeter_Flow_Rate_Multiplier_(ratio): 1.0 </setting>)
(<setting> speed Travel_Feed_Rate_(mm/s): 80.0 </setting>)
(</settings>)
(<timeStampPreface> 20121229_103825 </timeStampPreface>)
(<procedureName> carve </procedureName>)
(<procedureName> bottom </procedureName>)
(<procedureName> preface </procedureName>)
(<procedureName> inset </procedureName>)
(<procedureName> fill </procedureName>)
(<procedureName> speed </procedureName>)
(<procedureName> raft </procedureName>)
(<procedureName> skirt </procedureName>)
(<procedureName> chamber </procedureName>)
(<procedureName> jitter </procedureName>)
(<procedureName> comb </procedureName>)
(<procedureName> cool </procedureName>)
(<procedureName> dimension </procedureName>)
(<procedureName> alteration </procedureName>)
(<procedureName> export </procedureName>)
(</extruderInitialization>)
(<crafting>)
M140 S65.0
M141 S30.0
M142 S0.0
;M113 S1.0
;M108 R29.48
M73 P7 (display progress)
(<layer> 0.45 )
(<skirt>)
G1 X-4.9 Y4.2 Z0.45 F4800.0
G1 F1200.0
G1 E0.0
G1 F4800.0
M101
G1 X-2.78 Y5.6 Z0.45 F1238.041 E0.168
G1 X2.78 Y5.6 Z0.45 F1238.041 E0.535
G1 X4.9 Y4.2 Z0.45 F1238.041 E0.703
G1 X4.9 Y-4.2 Z0.45 F1238.041 E1.256
G1 X2.78 Y-5.6 Z0.45 F1238.041 E1.424
G1 X-2.78 Y-5.6 Z0.45 F1238.041 E1.791
G1 X-4.9 Y-4.2 Z0.45 F1238.041 E1.959
G1 X-4.9 Y4.2 Z0.45 F1238.041 E2.513
G1 F1200.0
G1 E2.513
G1 F1238.041
M103
;M108 R29.48
(</skirt>)
(<rotation> (0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-2.999 Z0.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z0.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z0.45 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z0.45 </boundaryPoint>)
(<edge> outer )
G1 X-2.1 Y-2.79 Z0.45 F4800.0
G1 F1200.0
G1 E2.513
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z0.45 F1238.041 E2.513
G1 X2.1 Y-2.8 Z0.45 F1238.041 E2.79
G1 X2.1 Y2.8 Z0.45 F1238.041 E3.16
G1 X-2.1 Y2.8 Z0.45 F1238.041 E3.437
G1 X-2.1 Y-2.79 Z0.45 F1238.041 E3.806
G1 F1200.0
G1 E3.806
G1 F1238.041
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-2.799 Z0.45 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z0.45 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z0.45 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z0.45 </infillPoint>)
(</infillBoundary>)
;M108 R14.74
G1 X-1.82 Y-1.82 Z0.45 F4800.0
G1 F1200.0
G1 E3.806
G1 F4800.0
M101
G1 X1.82 Y1.82 Z0.45 F1547.551 E3.942
G1 X1.77 Y2.34 Z0.45 F1547.551 E3.956
G1 X-1.82 Y-1.25 Z0.45 F1547.551 E4.09
G1 X-1.82 Y-0.69 Z0.45 F1547.551 E4.105
G1 X1.39 Y2.52 Z0.45 F1547.551 E4.225
G1 X0.82 Y2.52 Z0.45 F1547.551 E4.24
G1 X-1.82 Y-0.12 Z0.45 F1547.551 E4.338
G1 X-1.82 Y0.44 Z0.45 F1547.551 E4.353
G1 X0.26 Y2.52 Z0.45 F1547.551 E4.431
G1 X-0.31 Y2.52 Z0.45 F1547.551 E4.446
G1 X-1.82 Y1.01 Z0.45 F1547.551 E4.502
G1 X-1.82 Y1.57 Z0.45 F1547.551 E4.517
G1 X-0.88 Y2.52 Z0.45 F1547.551 E4.552
G1 X-1.44 Y2.52 Z0.45 F1547.551 E4.567
G1 X-1.82 Y2.14 Z0.45 F1547.551 E4.581
G1 F1200.0
G1 E4.581
G1 F1547.551
M103
G1 X1.82 Y1.25 Z0.45 F4800.0
G1 F1200.0
G1 E4.581
G1 F4800.0
M101
G1 X-1.77 Y-2.34 Z0.45 F1547.551 E4.715
G1 X-1.39 Y-2.52 Z0.45 F1547.551 E4.727
G1 X1.82 Y0.69 Z0.45 F1547.551 E4.846
G1 X1.82 Y0.12 Z0.45 F1547.551 E4.861
G1 X-0.82 Y-2.52 Z0.45 F1547.551 E4.96
G1 X-0.26 Y-2.52 Z0.45 F1547.551 E4.975
G1 X1.82 Y-0.44 Z0.45 F1547.551 E5.052
G1 X1.82 Y-1.01 Z0.45 F1547.551 E5.067
G1 X0.31 Y-2.52 Z0.45 F1547.551 E5.124
G1 X0.88 Y-2.52 Z0.45 F1547.551 E5.139
G1 X1.82 Y-1.57 Z0.45 F1547.551 E5.174
G1 X1.82 Y-2.14 Z0.45 F1547.551 E5.189
G1 X1.44 Y-2.52 Z0.45 F1547.551 E5.203
G1 F1200.0
G1 E5.203
G1 F1547.551
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R23.5
(</layer>)
M73 P11 (display progress)
(<layer> 0.7 )
(<skirt>)
G1 X-4.9 Y4.2 Z0.7 F4800.0
G1 F1200.0
G1 E5.203
G1 F4800.0
M101
G1 X-2.78 Y5.6 Z0.7 F1410.102 E5.32
G1 X2.78 Y5.6 Z0.7 F1410.102 E5.578
G1 X4.9 Y4.2 Z0.7 F1410.102 E5.695
G1 X4.9 Y-4.2 Z0.7 F1410.102 E6.082
G1 X2.78 Y-5.6 Z0.7 F1410.102 E6.2
G1 X-2.78 Y-5.6 Z0.7 F1410.102 E6.457
G1 X-4.9 Y-4.2 Z0.7 F1410.102 E6.574
G1 X-4.9 Y4.2 Z0.7 F1410.102 E6.962
G1 F1200.0
G1 E6.962
G1 F1410.102
M103
(</skirt>)
(<rotation> (-0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-2.999 Z0.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z0.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z0.7 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z0.7 </boundaryPoint>)
(<edge> outer )
G1 X-2.1 Y-2.49 Z0.7 F4800.0
G1 F1200.0
G1 E6.962
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z0.7 F1410.102 E6.976
G1 X2.1 Y-2.8 Z0.7 F1410.102 E7.17
G1 X2.1 Y2.8 Z0.7 F1410.102 E7.429
G1 X-2.1 Y2.8 Z0.7 F1410.102 E7.623
G1 X-2.1 Y-2.49 Z0.7 F1410.102 E7.867
G1 F1200.0
G1 E7.867
G1 F1410.102
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-2.799 Z0.7 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z0.7 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z0.7 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z0.7 </infillPoint>)
(</infillBoundary>)
G1 X-1.82 Y1.25 Z0.7 F4800.0
G1 F1200.0
G1 E7.867
G1 F4800.0
M101
G1 X1.77 Y-2.34 Z0.7 F1410.102 E8.102
G1 X1.39 Y-2.52 Z0.7 F1410.102 E8.121
G1 X-1.82 Y0.69 Z0.7 F1410.102 E8.331
G1 X-1.82 Y0.12 Z0.7 F1410.102 E8.357
G1 X0.82 Y-2.52 Z0.7 F1410.102 E8.529
G1 X0.26 Y-2.52 Z0.7 F1410.102 E8.556
G1 X-1.82 Y-0.44 Z0.7 F1410.102 E8.691
G1 X-1.82 Y-1.01 Z0.7 F1410.102 E8.717
G1 X-0.31 Y-2.52 Z0.7 F1410.102 E8.816
G1 X-0.88 Y-2.52 Z0.7 F1410.102 E8.842
G1 X-1.82 Y-1.57 Z0.7 F1410.102 E8.904
G1 X-1.82 Y-2.14 Z0.7 F1410.102 E8.93
G1 X-1.44 Y-2.52 Z0.7 F1410.102 E8.955
G1 F1200.0
G1 E8.955
G1 F1410.102
M103
G1 X1.82 Y-1.82 Z0.7 F4800.0
G1 F1200.0
G1 E8.955
G1 F4800.0
M101
G1 X-1.82 Y1.82 Z0.7 F1410.102 E9.193
G1 X-1.77 Y2.34 Z0.7 F1410.102 E9.217
G1 X1.82 Y-1.25 Z0.7 F1410.102 E9.451
G1 X1.82 Y-0.69 Z0.7 F1410.102 E9.477
G1 X-1.39 Y2.52 Z0.7 F1410.102 E9.687
G1 X-0.82 Y2.52 Z0.7 F1410.102 E9.713
G1 X1.82 Y-0.12 Z0.7 F1410.102 E9.886
G1 X1.82 Y0.44 Z0.7 F1410.102 E9.912
G1 X-0.26 Y2.52 Z0.7 F1410.102 E10.047
G1 X0.31 Y2.52 Z0.7 F1410.102 E10.074
G1 X1.82 Y1.01 Z0.7 F1410.102 E10.172
G1 X1.82 Y1.57 Z0.7 F1410.102 E10.198
G1 X0.88 Y2.52 Z0.7 F1410.102 E10.26
G1 X1.44 Y2.52 Z0.7 F1410.102 E10.286
G1 X1.82 Y2.14 Z0.7 F1410.102 E10.311
G1 F1200.0
G1 E10.311
G1 F1410.102
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R14.91
(</layer>)
(<operatingLayerEnd> </operatingLayerEnd>)
M73 P14 (display progress)
(<layer> 0.95 )
(<rotation> (0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-2.999 Z0.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z0.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z0.95 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z0.95 </boundaryPoint>)
(<edge> outer )
G1 X-1.92 Y-2.8 Z0.95 F4800.0
G1 F1200.0
G1 E10.311
G1 F4800.0
M101
M321
G1 X2.1 Y-2.8 Z0.95 F894.562 E10.497
G1 X2.1 Y2.8 Z0.95 F894.562 E10.755
G1 X-2.1 Y2.8 Z0.95 F894.562 E10.949
G1 X-2.1 Y-2.8 Z0.95 F894.562 E11.208
G1 X-1.92 Y-2.8 Z0.95 F894.562 E11.216
G1 F1200.0
G1 E11.216
G1 F894.562
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-2.799 Z0.95 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z0.95 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z0.95 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z0.95 </infillPoint>)
(</infillBoundary>)
G1 X-1.82 Y-1.82 Z0.95 F4800.0
G1 F1200.0
G1 E11.216
G1 F4800.0
M101
G1 X1.82 Y1.82 Z0.95 F894.562 E11.454
G1 X1.77 Y2.34 Z0.95 F894.562 E11.478
G1 X-1.82 Y-1.25 Z0.95 F894.562 E11.713
G1 X-1.82 Y-0.69 Z0.95 F894.562 E11.739
G1 X1.39 Y2.52 Z0.95 F894.562 E11.949
G1 X0.82 Y2.52 Z0.95 F894.562 E11.975
G1 X-1.82 Y-0.12 Z0.95 F894.562 E12.147
G1 X-1.82 Y0.44 Z0.95 F894.562 E12.173
G1 X0.26 Y2.52 Z0.95 F894.562 E12.309
G1 X-0.31 Y2.52 Z0.95 F894.562 E12.335
G1 X-1.82 Y1.01 Z0.95 F894.562 E12.434
G1 X-1.82 Y1.57 Z0.95 F894.562 E12.46
G1 X-0.88 Y2.52 Z0.95 F894.562 E12.522
G1 X-1.44 Y2.52 Z0.95 F894.562 E12.548
G1 X-1.82 Y2.14 Z0.95 F894.562 E12.573
G1 F1200.0
G1 E12.573
G1 F894.562
M103
G1 X1.82 Y1.25 Z0.95 F4800.0
G1 F1200.0
G1 E12.573
G1 F4800.0
M101
G1 X-1.77 Y-2.34 Z0.95 F894.562 E12.807
G1 X-1.39 Y-2.52 Z0.95 F894.562 E12.827
G1 X1.82 Y0.69 Z0.95 F894.562 E13.037
G1 X1.82 Y0.12 Z0.95 F894.562 E13.063
G1 X-0.82 Y-2.52 Z0.95 F894.562 E13.235
G1 X-0.26 Y-2.52 Z0.95 F894.562 E13.262
G1 X1.82 Y-0.44 Z0.95 F894.562 E13.397
G1 X1.82 Y-1.01 Z0.95 F894.562 E13.423
G1 X0.31 Y-2.52 Z0.95 F894.562 E13.522
G1 X0.88 Y-2.52 Z0.95 F894.562 E13.548
G1 X1.82 Y-1.57 Z0.95 F894.562 E13.61
G1 X1.82 Y-2.14 Z0.95 F894.562 E13.636
G1 X1.44 Y-2.52 Z0.95 F894.562 E13.661
G1 F1200.0
G1 E13.661
G1 F894.562
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R10.41
(</layer>)
M73 P17 (display progress)
(<layer> 1.2 )
(<rotation> (-0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-0.977 Z1.2 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-2.999 Z1.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z1.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-0.977 Z1.2 </boundaryPoint>)
(<edge> outer )
G1 X-2.1 Y-2.68 Z1.2 F4800.0
G1 F1200.0
G1 E13.661
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z1.2 F624.609 E13.666
G1 X2.1 Y-2.8 Z1.2 F624.609 E13.86
G1 X2.1 Y-1.18 Z1.2 F624.609 E13.935
G1 X-2.1 Y-1.18 Z1.2 F624.609 E14.129
G1 X-2.1 Y-2.68 Z1.2 F624.609 E14.199
G1 F1200.0
G1 E14.199
G1 F624.609
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-1.177 Z1.2 </infillPoint>)
(<infillPoint> X-2.1 Y-2.799 Z1.2 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z1.2 </infillPoint>)
(<infillPoint> X2.1 Y-1.177 Z1.2 </infillPoint>)
(</infillBoundary>)
G1 X1.82 Y-1.82 Z1.2 F4800.0
G1 F1200.0
G1 E14.199
G1 F4800.0
M101
G1 X1.46 Y-1.46 Z1.2 F624.609 E14.222
G1 X0.89 Y-1.46 Z1.2 F624.609 E14.249
G1 X1.77 Y-2.34 Z1.2 F624.609 E14.306
G1 X1.39 Y-2.52 Z1.2 F624.609 E14.326
G1 X0.33 Y-1.46 Z1.2 F624.609 E14.395
G1 X-0.24 Y-1.46 Z1.2 F624.609 E14.421
G1 X0.82 Y-2.52 Z1.2 F624.609 E14.491
G1 X0.26 Y-2.52 Z1.2 F624.609 E14.517
G1 X-0.81 Y-1.46 Z1.2 F624.609 E14.586
G1 X-1.37 Y-1.46 Z1.2 F624.609 E14.612
G1 X-0.31 Y-2.52 Z1.2 F624.609 E14.682
G1 X-0.88 Y-2.52 Z1.2 F624.609 E14.708
G1 X-1.76 Y-1.63 Z1.2 F624.609 E14.766
G1 X-1.82 Y-2.14 Z1.2 F624.609 E14.79
G1 X-1.44 Y-2.52 Z1.2 F624.609 E14.814
G1 F1200.0
G1 E14.814
G1 F624.609
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y0.977 Z1.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y0.977 Z1.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z1.2 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z1.2 </boundaryPoint>)
(<edge> outer )
G1 X-1.56 Y-2.98 Z1.2 F4800.0
G1 X-1.56 Y2.98 Z1.2 F4800.0
G1 X-1.56 Y1.18 Z1.2 F4800.0
G1 F1200.0
G1 E14.814
G1 F4800.0
M101
M321
G1 X-1.44 Y1.18 Z1.2 F624.609 E14.82
G1 X2.1 Y1.18 Z1.2 F624.609 E14.984
G1 X2.1 Y2.8 Z1.2 F624.609 E15.058
G1 X-2.1 Y2.8 Z1.2 F624.609 E15.253
G1 X-2.1 Y1.18 Z1.2 F624.609 E15.327
G1 X-1.56 Y1.18 Z1.2 F624.609 E15.352
G1 F1200.0
G1 E15.352
G1 F624.609
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y1.177 Z1.2 </infillPoint>)
(<infillPoint> X2.1 Y1.177 Z1.2 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z1.2 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z1.2 </infillPoint>)
(</infillBoundary>)
G1 X-1.46 Y1.46 Z1.2 F4800.0
G1 F1200.0
G1 E15.352
G1 F4800.0
M101
G1 X-1.82 Y1.82 Z1.2 F624.609 E15.376
G1 X-1.77 Y2.34 Z1.2 F624.609 E15.4
G1 X-0.89 Y1.46 Z1.2 F624.609 E15.458
G1 X-0.33 Y1.46 Z1.2 F624.609 E15.484
G1 X-1.39 Y2.52 Z1.2 F624.609 E15.553
G1 X-0.82 Y2.52 Z1.2 F624.609 E15.579
G1 X0.24 Y1.46 Z1.2 F624.609 E15.649
G1 X0.81 Y1.46 Z1.2 F624.609 E15.675
G1 X-0.26 Y2.52 Z1.2 F624.609 E15.744
G1 X0.31 Y2.52 Z1.2 F624.609 E15.77
G1 X1.37 Y1.46 Z1.2 F624.609 E15.84
G1 X1.76 Y1.63 Z1.2 F624.609 E15.859
G1 X0.88 Y2.52 Z1.2 F624.609 E15.918
G1 X1.44 Y2.52 Z1.2 F624.609 E15.944
G1 X1.82 Y2.14 Z1.2 F624.609 E15.968
G1 F1200.0
G1 E15.968
G1 F624.609
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R10.51
(</layer>)
M73 P22 (display progress)
(<layer> 1.45 )
(<rotation> (0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-0.977 Z1.45 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-2.999 Z1.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z1.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-0.977 Z1.45 </boundaryPoint>)
(<edge> outer )
G1 X-0.89 Y2.98 Z1.45 F4800.0
G1 X-0.89 Y-2.98 Z1.45 F4800.0
G1 X-2.1 Y-2.37 Z1.45 F4800.0
G1 F1200.0
G1 E15.968
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z1.45 F630.474 E15.988
G1 X2.1 Y-2.8 Z1.45 F630.474 E16.182
G1 X2.1 Y-1.18 Z1.45 F630.474 E16.257
G1 X-2.1 Y-1.18 Z1.45 F630.474 E16.451
G1 X-2.1 Y-2.37 Z1.45 F630.474 E16.506
G1 F1200.0
G1 E16.506
G1 F630.474
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-1.177 Z1.45 </infillPoint>)
(<infillPoint> X-2.1 Y-2.799 Z1.45 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z1.45 </infillPoint>)
(<infillPoint> X2.1 Y-1.177 Z1.45 </infillPoint>)
(</infillBoundary>)
G1 X-1.82 Y-1.82 Z1.45 F4800.0
G1 F1200.0
G1 E16.506
G1 F4800.0
M101
G1 X-1.46 Y-1.46 Z1.45 F630.474 E16.53
G1 X-0.89 Y-1.46 Z1.45 F630.474 E16.556
G1 X-1.77 Y-2.34 Z1.45 F630.474 E16.614
G1 X-1.39 Y-2.52 Z1.45 F630.474 E16.634
G1 X-0.33 Y-1.46 Z1.45 F630.474 E16.703
G1 X0.24 Y-1.46 Z1.45 F630.474 E16.729
G1 X-0.82 Y-2.52 Z1.45 F630.474 E16.799
G1 X-0.26 Y-2.52 Z1.45 F630.474 E16.825
G1 X0.81 Y-1.46 Z1.45 F630.474 E16.894
G1 X1.37 Y-1.46 Z1.45 F630.474 E16.92
G1 X0.31 Y-2.52 Z1.45 F630.474 E16.99
G1 X0.88 Y-2.52 Z1.45 F630.474 E17.016
G1 X1.76 Y-1.63 Z1.45 F630.474 E17.074
G1 X1.82 Y-2.14 Z1.45 F630.474 E17.098
G1 X1.44 Y-2.52 Z1.45 F630.474 E17.122
G1 F1200.0
G1 E17.122
G1 F630.474
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y0.977 Z1.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y0.977 Z1.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z1.45 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z1.45 </boundaryPoint>)
(<edge> outer )
G1 X1.04 Y-2.98 Z1.45 F4800.0
G1 X1.04 Y2.98 Z1.45 F4800.0
G1 X1.01 Y1.18 Z1.45 F4800.0
G1 F1200.0
G1 E17.122
G1 F4800.0
M101
M321
G1 X1.44 Y1.18 Z1.45 F630.474 E17.142
G1 X2.1 Y1.18 Z1.45 F630.474 E17.173
G1 X2.1 Y2.8 Z1.45 F630.474 E17.247
G1 X-2.1 Y2.8 Z1.45 F630.474 E17.442
G1 X-2.1 Y1.18 Z1.45 F630.474 E17.516
G1 X1.01 Y1.18 Z1.45 F630.474 E17.66
G1 F1200.0
G1 E17.66
G1 F630.474
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y1.177 Z1.45 </infillPoint>)
(<infillPoint> X2.1 Y1.177 Z1.45 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z1.45 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z1.45 </infillPoint>)
(</infillBoundary>)
G1 X1.46 Y1.46 Z1.45 F4800.0
G1 F1200.0
G1 E17.66
G1 F4800.0
M101
G1 X1.82 Y1.82 Z1.45 F630.474 E17.684
G1 X1.77 Y2.34 Z1.45 F630.474 E17.708
G1 X0.89 Y1.46 Z1.45 F630.474 E17.766
G1 X0.33 Y1.46 Z1.45 F630.474 E17.792
G1 X1.39 Y2.52 Z1.45 F630.474 E17.861
G1 X0.82 Y2.52 Z1.45 F630.474 E17.887
G1 X-0.24 Y1.46 Z1.45 F630.474 E17.957
G1 X-0.81 Y1.46 Z1.45 F630.474 E17.983
G1 X0.26 Y2.52 Z1.45 F630.474 E18.052
G1 X-0.31 Y2.52 Z1.45 F630.474 E18.078
G1 X-1.37 Y1.46 Z1.45 F630.474 E18.148
G1 X-1.76 Y1.63 Z1.45 F630.474 E18.168
G1 X-0.88 Y2.52 Z1.45 F630.474 E18.226
G1 X-1.44 Y2.52 Z1.45 F630.474 E18.252
G1 X-1.82 Y2.14 Z1.45 F630.474 E18.277
G1 F1200.0
G1 E18.277
G1 F630.474
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R10.51
(</layer>)
M73 P26 (display progress)
(<layer> 1.7 )
(<rotation> (-0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-0.977 Z1.7 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-2.999 Z1.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z1.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-0.977 Z1.7 </boundaryPoint>)
(<edge> outer )
G1 X-1.86 Y2.98 Z1.7 F4800.0
G1 X-1.86 Y-2.98 Z1.7 F4800.0
G1 X-2.03 Y-2.8 Z1.7 F4800.0
G1 F1200.0
G1 E18.277
G1 F4800.0
M101
M321
G1 X2.1 Y-2.8 Z1.7 F630.301 E18.468
G1 X2.1 Y-1.18 Z1.7 F630.301 E18.543
G1 X-2.1 Y-1.18 Z1.7 F630.301 E18.737
G1 X-2.1 Y-2.8 Z1.7 F630.301 E18.812
G1 X-2.03 Y-2.8 Z1.7 F630.301 E18.815
G1 F1200.0
G1 E18.815
G1 F630.301
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-1.177 Z1.7 </infillPoint>)
(<infillPoint> X-2.1 Y-2.799 Z1.7 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z1.7 </infillPoint>)
(<infillPoint> X2.1 Y-1.177 Z1.7 </infillPoint>)
(</infillBoundary>)
G1 X1.82 Y-1.82 Z1.7 F4800.0
G1 F1200.0
G1 E18.815
G1 F4800.0
M101
G1 X1.46 Y-1.46 Z1.7 F630.301 E18.839
G1 X0.89 Y-1.46 Z1.7 F630.301 E18.865
G1 X1.77 Y-2.34 Z1.7 F630.301 E18.922
G1 X1.39 Y-2.52 Z1.7 F630.301 E18.942
G1 X0.33 Y-1.46 Z1.7 F630.301 E19.011
G1 X-0.24 Y-1.46 Z1.7 F630.301 E19.038
G1 X0.82 Y-2.52 Z1.7 F630.301 E19.107
G1 X0.26 Y-2.52 Z1.7 F630.301 E19.133
G1 X-0.81 Y-1.46 Z1.7 F630.301 E19.203
G1 X-1.37 Y-1.46 Z1.7 F630.301 E19.229
G1 X-0.31 Y-2.52 Z1.7 F630.301 E19.298
G1 X-0.88 Y-2.52 Z1.7 F630.301 E19.324
G1 X-1.76 Y-1.63 Z1.7 F630.301 E19.382
G1 X-1.82 Y-2.14 Z1.7 F630.301 E19.406
G1 X-1.44 Y-2.52 Z1.7 F630.301 E19.431
G1 F1200.0
G1 E19.431
G1 F630.301
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y0.977 Z1.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y0.977 Z1.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z1.7 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z1.7 </boundaryPoint>)
(<edge> outer )
G1 X-1.38 Y-2.98 Z1.7 F4800.0
G1 X-1.38 Y2.98 Z1.7 F4800.0
G1 X-1.37 Y1.18 Z1.7 F4800.0
G1 F1200.0
G1 E19.431
G1 F4800.0
M101
M321
G1 X2.1 Y1.18 Z1.7 F630.301 E19.591
G1 X2.1 Y2.8 Z1.7 F630.301 E19.666
G1 X-2.1 Y2.8 Z1.7 F630.301 E19.86
G1 X-2.1 Y1.18 Z1.7 F630.301 E19.935
G1 X-1.44 Y1.18 Z1.7 F630.301 E19.966
G1 X-1.37 Y1.18 Z1.7 F630.301 E19.969
G1 F1200.0
G1 E19.969
G1 F630.301
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y1.177 Z1.7 </infillPoint>)
(<infillPoint> X2.1 Y1.177 Z1.7 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z1.7 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z1.7 </infillPoint>)
(</infillBoundary>)
G1 X-1.46 Y1.46 Z1.7 F4800.0
G1 F1200.0
G1 E19.969
G1 F4800.0
M101
G1 X-1.82 Y1.82 Z1.7 F630.301 E19.993
G1 X-1.77 Y2.34 Z1.7 F630.301 E20.017
G1 X-0.89 Y1.46 Z1.7 F630.301 E20.074
G1 X-0.33 Y1.46 Z1.7 F630.301 E20.1
G1 X-1.39 Y2.52 Z1.7 F630.301 E20.17
G1 X-0.82 Y2.52 Z1.7 F630.301 E20.196
G1 X0.24 Y1.46 Z1.7 F630.301 E20.265
G1 X0.81 Y1.46 Z1.7 F630.301 E20.292
G1 X-0.26 Y2.52 Z1.7 F630.301 E20.361
G1 X0.31 Y2.52 Z1.7 F630.301 E20.387
G1 X1.37 Y1.46 Z1.7 F630.301 E20.457
G1 X1.76 Y1.63 Z1.7 F630.301 E20.476
G1 X0.88 Y2.52 Z1.7 F630.301 E20.535
G1 X1.44 Y2.52 Z1.7 F630.301 E20.561
G1 X1.82 Y2.14 Z1.7 F630.301 E20.585
G1 F1200.0
G1 E20.585
G1 F630.301
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R9.132
(</layer>)
M73 P30 (display progress)
(<layer> 1.95 )
(<rotation> (0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.19 Y-2.999 Z1.95 </boundaryPoint>)
(<boundaryPoint> X-0.19 Y-0.977 Z1.95 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-0.977 Z1.95 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-2.999 Z1.95 </boundaryPoint>)
(<edge> outer )
G1 X-0.78 Y2.98 Z1.95 F4800.0
G1 X-0.78 Y-2.98 Z1.95 F4800.0
G1 X-2.1 Y-2.56 Z1.95 F4800.0
G1 F1200.0
G1 E20.585
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z1.95 F547.947 E20.597
G1 X-0.39 Y-2.8 Z1.95 F547.947 E20.676
G1 X-0.39 Y-1.18 Z1.95 F547.947 E20.75
G1 X-2.1 Y-1.18 Z1.95 F547.947 E20.829
G1 X-2.1 Y-2.56 Z1.95 F547.947 E20.893
G1 F1200.0
G1 E20.893
G1 F547.947
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.39 Y-2.799 Z1.95 </infillPoint>)
(<infillPoint> X-0.39 Y-1.177 Z1.95 </infillPoint>)
(<infillPoint> X-2.1 Y-1.177 Z1.95 </infillPoint>)
(<infillPoint> X-2.1 Y-2.799 Z1.95 </infillPoint>)
(</infillBoundary>)
G1 X-1.82 Y-1.82 Z1.95 F4800.0
G1 F1200.0
G1 E20.893
G1 F4800.0
M101
G1 X-1.46 Y-1.46 Z1.95 F547.947 E20.917
G1 X-0.9 Y-1.46 Z1.95 F547.947 E20.943
G1 X-1.77 Y-2.34 Z1.95 F547.947 E21.0
G1 X-1.39 Y-2.52 Z1.95 F547.947 E21.02
G1 X-0.67 Y-1.8 Z1.95 F547.947 E21.067
G1 F1200.0
G1 E21.067
G1 F547.947
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.191 Y-0.977 Z1.95 </boundaryPoint>)
(<boundaryPoint> X0.191 Y-2.999 Z1.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z1.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-0.977 Z1.95 </boundaryPoint>)
(<edge> outer )
G1 X-2.19 Y-1.61 Z1.95 F4800.0
G1 X2.19 Y-1.61 Z1.95 F4800.0
G1 X0.39 Y-1.56 Z1.95 F4800.0
G1 F1200.0
G1 E21.067
G1 F4800.0
M101
M321
G1 X0.39 Y-1.8 Z1.95 F547.947 E21.078
G1 X0.39 Y-2.8 Z1.95 F547.947 E21.124
G1 X2.1 Y-2.8 Z1.95 F547.947 E21.203
G1 X2.1 Y-1.18 Z1.95 F547.947 E21.278
G1 X0.39 Y-1.18 Z1.95 F547.947 E21.357
G1 X0.39 Y-1.56 Z1.95 F547.947 E21.375
G1 F1200.0
G1 E21.375
G1 F547.947
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X0.391 Y-1.177 Z1.95 </infillPoint>)
(<infillPoint> X0.391 Y-2.799 Z1.95 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z1.95 </infillPoint>)
(<infillPoint> X2.1 Y-1.177 Z1.95 </infillPoint>)
(</infillBoundary>)
G1 X0.67 Y-2.16 Z1.95 F4800.0
G1 F1200.0
G1 E21.375
G1 F4800.0
M101
G1 X1.37 Y-1.46 Z1.95 F547.947 E21.42
G1 X1.76 Y-1.63 Z1.95 F547.947 E21.44
G1 X0.89 Y-2.51 Z1.95 F547.947 E21.498
G1 X1.44 Y-2.52 Z1.95 F547.947 E21.523
G1 X1.82 Y-2.14 Z1.95 F547.947 E21.548
G1 F1200.0
G1 E21.548
G1 F547.947
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.191 Y2.999 Z1.95 </boundaryPoint>)
(<boundaryPoint> X0.191 Y0.977 Z1.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y0.977 Z1.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z1.95 </boundaryPoint>)
(<edge> outer )
G1 X1.59 Y-2.98 Z1.95 F4800.0
G1 X1.59 Y2.98 Z1.95 F4800.0
G1 X1.58 Y1.18 Z1.95 F4800.0
G1 F1200.0
G1 E21.548
G1 F4800.0
M101
M321
G1 X1.82 Y1.18 Z1.95 F547.947 E21.559
G1 X2.1 Y1.18 Z1.95 F547.947 E21.572
G1 X2.1 Y2.8 Z1.95 F547.947 E21.647
G1 X0.39 Y2.8 Z1.95 F547.947 E21.726
G1 X0.39 Y1.18 Z1.95 F547.947 E21.801
G1 X1.58 Y1.18 Z1.95 F547.947 E21.856
G1 F1200.0
G1 E21.856
G1 F547.947
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X0.391 Y2.799 Z1.95 </infillPoint>)
(<infillPoint> X0.391 Y1.177 Z1.95 </infillPoint>)
(<infillPoint> X2.1 Y1.177 Z1.95 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z1.95 </infillPoint>)
(</infillBoundary>)
G1 X1.46 Y1.46 Z1.95 F4800.0
G1 F1200.0
G1 E21.856
G1 F4800.0
M101
G1 X1.82 Y1.82 Z1.95 F547.947 E21.879
G1 X1.77 Y2.34 Z1.95 F547.947 E21.903
G1 X0.9 Y1.46 Z1.95 F547.947 E21.961
G1 X0.67 Y1.8 Z1.95 F547.947 E21.98
G1 X1.39 Y2.52 Z1.95 F547.947 E22.026
G1 F1200.0
G1 E22.026
G1 F547.947
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.19 Y2.999 Z1.95 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z1.95 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y0.977 Z1.95 </boundaryPoint>)
(<boundaryPoint> X-0.19 Y0.977 Z1.95 </boundaryPoint>)
(<edge> outer )
G1 X2.19 Y2.31 Z1.95 F4800.0
G1 X-2.19 Y2.31 Z1.95 F4800.0
G1 X-0.39 Y2.28 Z1.95 F4800.0
G1 F1200.0
G1 E22.026
G1 F4800.0
M101
M321
G1 X-0.39 Y2.52 Z1.95 F547.947 E22.037
G1 X-0.39 Y2.8 Z1.95 F547.947 E22.05
G1 X-2.1 Y2.8 Z1.95 F547.947 E22.129
G1 X-2.1 Y1.18 Z1.95 F547.947 E22.204
G1 X-0.39 Y1.18 Z1.95 F547.947 E22.283
G1 X-0.39 Y2.28 Z1.95 F547.947 E22.334
G1 F1200.0
G1 E22.334
G1 F547.947
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-0.39 Y2.799 Z1.95 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z1.95 </infillPoint>)
(<infillPoint> X-2.1 Y1.177 Z1.95 </infillPoint>)
(<infillPoint> X-0.39 Y1.177 Z1.95 </infillPoint>)
(</infillBoundary>)
G1 X-0.67 Y2.16 Z1.95 F4800.0
G1 F1200.0
G1 E22.334
G1 F4800.0
M101
G1 X-1.37 Y1.46 Z1.95 F547.947 E22.38
G1 X-1.76 Y1.63 Z1.95 F547.947 E22.4
G1 X-0.89 Y2.51 Z1.95 F547.947 E22.457
G1 X-1.44 Y2.52 Z1.95 F547.947 E22.483
G1 X-1.82 Y2.14 Z1.95 F547.947 E22.508
G1 F1200.0
G1 E22.508
G1 F547.947
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R6.712
(</layer>)
M73 P37 (display progress)
(<layer> 2.2 )
(<rotation> (-0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-2.999 Z2.2 </boundaryPoint>)
(<boundaryPoint> X-0.684 Y-2.999 Z2.2 </boundaryPoint>)
(<boundaryPoint> X-0.674 Y-0.971 Z2.2 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-0.971 Z2.2 </boundaryPoint>)
(<edge> outer )
G1 X-1.84 Y2.98 Z2.2 F4800.0
G1 X-1.84 Y-2.98 Z2.2 F4800.0
G1 X-1.84 Y-2.8 Z2.2 F4800.0
G1 F1200.0
G1 E22.508
G1 F4800.0
M101
M321
G1 X-0.88 Y-2.8 Z2.2 F402.725 E22.552
G1 X-0.88 Y-1.17 Z2.2 F402.725 E22.627
G1 X-2.1 Y-1.17 Z2.2 F402.725 E22.684
G1 X-2.1 Y-2.8 Z2.2 F402.725 E22.759
G1 X-1.84 Y-2.8 Z2.2 F402.725 E22.771
G1 F1200.0
G1 E22.771
G1 F402.725
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-2.799 Z2.2 </infillPoint>)
(<infillPoint> X-0.883 Y-2.799 Z2.2 </infillPoint>)
(<infillPoint> X-0.875 Y-1.171 Z2.2 </infillPoint>)
(<infillPoint> X-2.1 Y-1.171 Z2.2 </infillPoint>)
(</infillBoundary>)
G1 X-1.16 Y-2.23 Z2.2 F4800.0
G1 F1200.0
G1 E22.771
G1 F4800.0
M101
G1 X-1.77 Y-1.63 Z2.2 F402.725 E22.811
G1 X-1.82 Y-2.14 Z2.2 F402.725 E22.834
G1 X-1.44 Y-2.52 Z2.2 F402.725 E22.859
G1 F1200.0
G1 E22.859
G1 F402.725
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.686 Y-2.999 Z2.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z2.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-0.971 Z2.2 </boundaryPoint>)
(<boundaryPoint> X0.686 Y-0.971 Z2.2 </boundaryPoint>)
(<edge> outer )
G1 X-2.28 Y-2.5 Z2.2 F4800.0
G1 X2.29 Y-2.5 Z2.2 F4800.0
G1 X0.89 Y-2.77 Z2.2 F4800.0
G1 F1200.0
G1 E22.859
G1 F4800.0
M101
M321
G1 X0.89 Y-2.8 Z2.2 F402.725 E22.86
G1 X2.1 Y-2.8 Z2.2 F402.725 E22.916
G1 X2.1 Y-1.17 Z2.2 F402.725 E22.992
G1 X0.89 Y-1.17 Z2.2 F402.725 E23.048
G1 X0.89 Y-2.52 Z2.2 F402.725 E23.11
G1 X0.89 Y-2.77 Z2.2 F402.725 E23.122
G1 F1200.0
G1 E23.122
G1 F402.725
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X0.886 Y-2.799 Z2.2 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z2.2 </infillPoint>)
(<infillPoint> X2.1 Y-1.171 Z2.2 </infillPoint>)
(<infillPoint> X0.886 Y-1.171 Z2.2 </infillPoint>)
(</infillBoundary>)
G1 X1.82 Y-1.82 Z2.2 F4800.0
G1 F1200.0
G1 E23.122
G1 F4800.0
M101
G1 X1.45 Y-1.45 Z2.2 F402.725 E23.146
G1 X1.17 Y-1.73 Z2.2 F402.725 E23.164
G1 X1.77 Y-2.34 Z2.2 F402.725 E23.204
G1 F1200.0
G1 E23.204
G1 F402.725
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X2.3 Y2.999 Z2.2 </boundaryPoint>)
(<boundaryPoint> X0.686 Y2.999 Z2.2 </boundaryPoint>)
(<boundaryPoint> X0.686 Y1.337 Z2.2 </boundaryPoint>)
(<boundaryPoint> X0.777 Y0.974 Z2.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y0.971 Z2.2 </boundaryPoint>)
(<edge> outer )
G1 X1.82 Y-2.97 Z2.2 F4800.0
G1 X1.83 Y2.97 Z2.2 F4800.0
G1 X2.04 Y1.17 Z2.2 F4800.0
G1 F1200.0
G1 E23.204
G1 F4800.0
M101
M321
G1 X2.1 Y1.17 Z2.2 F402.725 E23.207
G1 X2.1 Y2.8 Z2.2 F402.725 E23.282
G1 X0.89 Y2.8 Z2.2 F402.725 E23.338
G1 X0.89 Y1.36 Z2.2 F402.725 E23.404
G1 X0.93 Y1.17 Z2.2 F402.725 E23.413
G1 X1.78 Y1.17 Z2.2 F402.725 E23.453
G1 X2.04 Y1.17 Z2.2 F402.725 E23.464
G1 F1200.0
G1 E23.464
G1 F402.725
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X2.1 Y2.799 Z2.2 </infillPoint>)
(<infillPoint> X0.886 Y2.799 Z2.2 </infillPoint>)
(<infillPoint> X0.886 Y1.362 Z2.2 </infillPoint>)
(<infillPoint> X0.933 Y1.174 Z2.2 </infillPoint>)
(<infillPoint> X2.1 Y1.171 Z2.2 </infillPoint>)
(</infillBoundary>)
G1 X1.17 Y1.66 Z2.2 F4800.0
G1 F1200.0
G1 E23.464
G1 F4800.0
M101
G1 X1.37 Y1.46 Z2.2 F402.725 E23.478
G1 X1.77 Y1.63 Z2.2 F402.725 E23.498
G1 X1.17 Y2.23 Z2.2 F402.725 E23.537
G1 X1.44 Y2.52 Z2.2 F402.725 E23.555
G1 X1.82 Y2.14 Z2.2 F402.725 E23.58
G1 F1200.0
G1 E23.58
G1 F402.725
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y2.999 Z2.2 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y0.977 Z2.2 </boundaryPoint>)
(<boundaryPoint> X-0.684 Y0.977 Z2.2 </boundaryPoint>)
(<boundaryPoint> X-0.684 Y2.999 Z2.2 </boundaryPoint>)
(<edge> outer )
G1 X2.29 Y2.38 Z2.2 F4800.0
G1 X-2.28 Y2.38 Z2.2 F4800.0
G1 X-0.88 Y2.4 Z2.2 F4800.0
G1 F1200.0
G1 E23.58
G1 F4800.0
M101
M321
G1 X-0.88 Y2.8 Z2.2 F402.725 E23.599
G1 X-2.1 Y2.8 Z2.2 F402.725 E23.655
G1 X-2.1 Y1.18 Z2.2 F402.725 E23.73
G1 X-0.88 Y1.18 Z2.2 F402.725 E23.786
G1 X-0.88 Y2.14 Z2.2 F402.725 E23.831
G1 X-0.88 Y2.4 Z2.2 F402.725 E23.842
G1 F1200.0
G1 E23.842
G1 F402.725
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y2.799 Z2.2 </infillPoint>)
(<infillPoint> X-2.1 Y1.177 Z2.2 </infillPoint>)
(<infillPoint> X-0.884 Y1.177 Z2.2 </infillPoint>)
(<infillPoint> X-0.884 Y2.799 Z2.2 </infillPoint>)
(</infillBoundary>)
G1 X-1.46 Y1.46 Z2.2 F4800.0
G1 F1200.0
G1 E23.842
G1 F4800.0
M101
G1 X-1.82 Y1.82 Z2.2 F402.725 E23.866
G1 X-1.77 Y2.34 Z2.2 F402.725 E23.89
G1 X-1.16 Y1.73 Z2.2 F402.725 E23.93
G1 F1200.0
G1 E23.93
G1 F402.725
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R5.852
(</layer>)
M73 P44 (display progress)
(<layer> 2.45 )
(<rotation> (0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-2.999 Z2.45 </boundaryPoint>)
(<boundaryPoint> X-0.876 Y-2.999 Z2.45 </boundaryPoint>)
(<boundaryPoint> X-0.876 Y-0.984 Z2.45 </boundaryPoint>)
(<boundaryPoint> X-1.94 Y-0.983 Z2.45 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-1.067 Z2.45 </boundaryPoint>)
(<edge> outer )
G1 X-1.73 Y2.98 Z2.45 F4800.0
G1 X-1.73 Y-2.97 Z2.45 F4800.0
G1 X-2.1 Y-2.75 Z2.45 F4800.0
G1 F1200.0
G1 E23.93
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z2.45 F351.107 E23.932
G1 X-1.08 Y-2.8 Z2.45 F351.107 E23.979
G1 X-1.08 Y-1.18 Z2.45 F351.107 E24.054
G1 X-1.92 Y-1.18 Z2.45 F351.107 E24.093
G1 X-2.1 Y-1.23 Z2.45 F351.107 E24.102
G1 X-2.1 Y-2.75 Z2.45 F351.107 E24.172
G1 F1200.0
G1 E24.172
G1 F351.107
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-2.799 Z2.45 </infillPoint>)
(<infillPoint> X-1.076 Y-2.799 Z2.45 </infillPoint>)
(<infillPoint> X-1.076 Y-1.184 Z2.45 </infillPoint>)
(<infillPoint> X-1.917 Y-1.183 Z2.45 </infillPoint>)
(<infillPoint> X-2.1 Y-1.226 Z2.45 </infillPoint>)
(</infillBoundary>)
G1 X-1.82 Y-1.82 Z2.45 F4800.0
G1 F1200.0
G1 E24.172
G1 F4800.0
M101
G1 X-1.52 Y-1.52 Z2.45 F351.107 E24.191
G1 X-1.36 Y-1.92 Z2.45 F351.107 E24.211
G1 X-1.77 Y-2.34 Z2.45 F351.107 E24.238
G1 F1200.0
G1 E24.238
G1 F351.107
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.876 Y-2.999 Z2.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z2.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-0.983 Z2.45 </boundaryPoint>)
(<boundaryPoint> X0.877 Y-0.984 Z2.45 </boundaryPoint>)
(<edge> outer )
G1 X-2.28 Y-2.29 Z2.45 F4800.0
G1 X2.28 Y-2.3 Z2.45 F4800.0
G1 X1.08 Y-2.29 Z2.45 F4800.0
G1 F1200.0
G1 E24.238
G1 F4800.0
M101
M321
G1 X1.08 Y-2.34 Z2.45 F351.107 E24.241
G1 X1.08 Y-2.8 Z2.45 F351.107 E24.262
G1 X2.1 Y-2.8 Z2.45 F351.107 E24.309
G1 X2.1 Y-1.18 Z2.45 F351.107 E24.384
G1 X1.08 Y-1.18 Z2.45 F351.107 E24.431
G1 X1.08 Y-2.29 Z2.45 F351.107 E24.482
G1 F1200.0
G1 E24.482
G1 F351.107
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X1.076 Y-2.799 Z2.45 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z2.45 </infillPoint>)
(<infillPoint> X2.1 Y-1.183 Z2.45 </infillPoint>)
(<infillPoint> X1.077 Y-1.184 Z2.45 </infillPoint>)
(</infillBoundary>)
G1 X1.36 Y-2.04 Z2.45 F4800.0
G1 F1200.0
G1 E24.482
G1 F4800.0
M101
G1 X1.76 Y-1.63 Z2.45 F351.107 E24.509
G1 X1.82 Y-2.14 Z2.45 F351.107 E24.532
G1 X1.51 Y-2.44 Z2.45 F351.107 E24.552
G1 F1200.0
G1 E24.552
G1 F351.107
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X2.3 Y0.984 Z2.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z2.45 </boundaryPoint>)
(<boundaryPoint> X0.876 Y2.999 Z2.45 </boundaryPoint>)
(<boundaryPoint> X0.877 Y0.984 Z2.45 </boundaryPoint>)
(<edge> outer )
G1 X1.47 Y-2.98 Z2.45 F4800.0
G1 X1.47 Y2.98 Z2.45 F4800.0
G1 X1.47 Y1.18 Z2.45 F4800.0
G1 F1200.0
G1 E24.552
G1 F4800.0
M101
M321
G1 X1.51 Y1.18 Z2.45 F351.107 E24.555
G1 X2.1 Y1.18 Z2.45 F351.107 E24.582
G1 X2.1 Y2.8 Z2.45 F351.107 E24.656
G1 X1.08 Y2.8 Z2.45 F351.107 E24.703
G1 X1.08 Y1.18 Z2.45 F351.107 E24.778
G1 X1.47 Y1.18 Z2.45 F351.107 E24.796
G1 F1200.0
G1 E24.796
G1 F351.107
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X2.1 Y1.184 Z2.45 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z2.45 </infillPoint>)
(<infillPoint> X1.076 Y2.799 Z2.45 </infillPoint>)
(<infillPoint> X1.077 Y1.184 Z2.45 </infillPoint>)
(</infillBoundary>)
G1 X1.53 Y1.53 Z2.45 F4800.0
G1 F1200.0
G1 E24.796
G1 F4800.0
M101
G1 X1.82 Y1.82 Z2.45 F351.107 E24.815
G1 X1.36 Y1.92 Z2.45 F351.107 E24.837
G1 X1.77 Y2.34 Z2.45 F351.107 E24.864
G1 F1200.0
G1 E24.864
G1 F351.107
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.876 Y2.999 Z2.45 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z2.45 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y0.983 Z2.45 </boundaryPoint>)
(<boundaryPoint> X-0.876 Y0.984 Z2.45 </boundaryPoint>)
(<edge> outer )
G1 X2.28 Y2.29 Z2.45 F4800.0
G1 X-2.28 Y2.29 Z2.45 F4800.0
G1 X-1.08 Y2.29 Z2.45 F4800.0
G1 F1200.0
G1 E24.864
G1 F4800.0
M101
M321
G1 X-1.08 Y2.34 Z2.45 F351.107 E24.866
G1 X-1.08 Y2.8 Z2.45 F351.107 E24.888
G1 X-2.1 Y2.8 Z2.45 F351.107 E24.935
G1 X-2.1 Y1.18 Z2.45 F351.107 E25.01
G1 X-1.08 Y1.18 Z2.45 F351.107 E25.057
G1 X-1.08 Y2.29 Z2.45 F351.107 E25.108
G1 F1200.0
G1 E25.108
G1 F351.107
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-1.076 Y2.799 Z2.45 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z2.45 </infillPoint>)
(<infillPoint> X-2.1 Y1.183 Z2.45 </infillPoint>)
(<infillPoint> X-1.076 Y1.184 Z2.45 </infillPoint>)
(</infillBoundary>)
G1 X-1.36 Y2.04 Z2.45 F4800.0
G1 F1200.0
G1 E25.108
G1 F4800.0
M101
G1 X-1.76 Y1.63 Z2.45 F351.107 E25.134
G1 X-1.82 Y2.14 Z2.45 F351.107 E25.158
G1 X-1.51 Y2.44 Z2.45 F351.107 E25.178
G1 F1200.0
G1 E25.178
G1 F351.107
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R5.286
(</layer>)
M73 P51 (display progress)
(<layer> 2.7 )
(<rotation> (-0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-2.999 Z2.7 </boundaryPoint>)
(<boundaryPoint> X-0.971 Y-2.999 Z2.7 </boundaryPoint>)
(<boundaryPoint> X-0.971 Y-1.07 Z2.7 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-1.071 Z2.7 </boundaryPoint>)
(<edge> outer )
G1 X-1.88 Y2.98 Z2.7 F4800.0
G1 X-1.89 Y-2.98 Z2.7 F4800.0
G1 X-2.1 Y-2.44 Z2.7 F4800.0
G1 F1200.0
G1 E25.178
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z2.7 F317.165 E25.194
G1 X-1.17 Y-2.8 Z2.7 F317.165 E25.237
G1 X-1.17 Y-1.27 Z2.7 F317.165 E25.308
G1 X-2.1 Y-1.27 Z2.7 F317.165 E25.351
G1 X-2.1 Y-2.44 Z2.7 F317.165 E25.405
G1 F1200.0
G1 E25.405
G1 F317.165
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-2.799 Z2.7 </infillPoint>)
(<infillPoint> X-1.171 Y-2.799 Z2.7 </infillPoint>)
(<infillPoint> X-1.171 Y-1.27 Z2.7 </infillPoint>)
(<infillPoint> X-2.1 Y-1.271 Z2.7 </infillPoint>)
(</infillBoundary>)
G1 X-1.45 Y-1.94 Z2.7 F4800.0
G1 F1200.0
G1 E25.405
G1 F4800.0
M101
G1 X-1.72 Y-1.68 Z2.7 F317.165 E25.422
G1 X-1.82 Y-2.14 Z2.7 F317.165 E25.444
G1 X-1.56 Y-2.4 Z2.7 F317.165 E25.461
G1 F1200.0
G1 E25.461
G1 F317.165
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.971 Y-1.07 Z2.7 </boundaryPoint>)
(<boundaryPoint> X0.971 Y-2.999 Z2.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z2.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-1.071 Z2.7 </boundaryPoint>)
(<edge> outer )
G1 X-2.17 Y-2.07 Z2.7 F4800.0
G1 X2.17 Y-2.07 Z2.7 F4800.0
G1 X1.17 Y-2.04 Z2.7 F4800.0
G1 F1200.0
G1 E25.461
G1 F4800.0
M101
M321
G1 X1.17 Y-2.4 Z2.7 F317.165 E25.478
G1 X1.17 Y-2.8 Z2.7 F317.165 E25.496
G1 X2.1 Y-2.8 Z2.7 F317.165 E25.539
G1 X2.1 Y-1.27 Z2.7 F317.165 E25.61
G1 X1.17 Y-1.27 Z2.7 F317.165 E25.653
G1 X1.17 Y-2.04 Z2.7 F317.165 E25.688
G1 F1200.0
G1 E25.688
G1 F317.165
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X1.171 Y-1.27 Z2.7 </infillPoint>)
(<infillPoint> X1.171 Y-2.799 Z2.7 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z2.7 </infillPoint>)
(<infillPoint> X2.1 Y-1.271 Z2.7 </infillPoint>)
(</infillBoundary>)
G1 X1.82 Y-1.82 Z2.7 F4800.0
G1 F1200.0
G1 E25.688
G1 F4800.0
M101
G1 X1.61 Y-1.61 Z2.7 F317.165 E25.702
G1 X1.45 Y-2.02 Z2.7 F317.165 E25.722
G1 X1.77 Y-2.34 Z2.7 F317.165 E25.743
G1 F1200.0
G1 E25.743
G1 F317.165
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X2.3 Y1.071 Z2.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z2.7 </boundaryPoint>)
(<boundaryPoint> X0.971 Y2.999 Z2.7 </boundaryPoint>)
(<boundaryPoint> X0.971 Y1.07 Z2.7 </boundaryPoint>)
(<edge> outer )
G1 X1.43 Y-2.87 Z2.7 F4800.0
G1 X1.43 Y2.87 Z2.7 F4800.0
G1 X1.41 Y1.27 Z2.7 F4800.0
G1 F1200.0
G1 E25.743
G1 F4800.0
M101
M321
G1 X1.77 Y1.27 Z2.7 F317.165 E25.759
G1 X2.1 Y1.27 Z2.7 F317.165 E25.775
G1 X2.1 Y2.8 Z2.7 F317.165 E25.845
G1 X1.17 Y2.8 Z2.7 F317.165 E25.888
G1 X1.17 Y1.27 Z2.7 F317.165 E25.959
G1 X1.41 Y1.27 Z2.7 F317.165 E25.97
G1 F1200.0
G1 E25.97
G1 F317.165
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X2.1 Y1.271 Z2.7 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z2.7 </infillPoint>)
(<infillPoint> X1.171 Y2.799 Z2.7 </infillPoint>)
(<infillPoint> X1.171 Y1.27 Z2.7 </infillPoint>)
(</infillBoundary>)
G1 X1.45 Y1.94 Z2.7 F4800.0
G1 F1200.0
G1 E25.97
G1 F4800.0
M101
G1 X1.72 Y1.68 Z2.7 F317.165 E25.987
G1 X1.82 Y2.14 Z2.7 F317.165 E26.009
G1 X1.56 Y2.4 Z2.7 F317.165 E26.026
G1 F1200.0
G1 E26.026
G1 F317.165
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.971 Y1.07 Z2.7 </boundaryPoint>)
(<boundaryPoint> X-0.971 Y2.999 Z2.7 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z2.7 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y1.071 Z2.7 </boundaryPoint>)
(<edge> outer )
G1 X2.17 Y2.07 Z2.7 F4800.0
G1 X-2.17 Y2.07 Z2.7 F4800.0
G1 X-1.17 Y2.04 Z2.7 F4800.0
G1 F1200.0
G1 E26.026
G1 F4800.0
M101
M321
G1 X-1.17 Y2.4 Z2.7 F317.165 E26.043
G1 X-1.17 Y2.8 Z2.7 F317.165 E26.061
G1 X-2.1 Y2.8 Z2.7 F317.165 E26.104
G1 X-2.1 Y1.27 Z2.7 F317.165 E26.175
G1 X-1.17 Y1.27 Z2.7 F317.165 E26.218
G1 X-1.17 Y2.04 Z2.7 F317.165 E26.253
G1 F1200.0
G1 E26.253
G1 F317.165
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-1.171 Y1.27 Z2.7 </infillPoint>)
(<infillPoint> X-1.171 Y2.799 Z2.7 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z2.7 </infillPoint>)
(<infillPoint> X-2.1 Y1.271 Z2.7 </infillPoint>)
(</infillBoundary>)
G1 X-1.61 Y1.61 Z2.7 F4800.0
G1 F1200.0
G1 E26.253
G1 F4800.0
M101
G1 X-1.82 Y1.82 Z2.7 F317.165 E26.267
G1 X-1.45 Y2.02 Z2.7 F317.165 E26.286
G1 X-1.77 Y2.34 Z2.7 F317.165 E26.307
G1 F1200.0
G1 E26.307
G1 F317.165
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R5.105
(</layer>)
M73 P58 (display progress)
(<layer> 2.95 )
(<rotation> (0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-2.999 Z2.95 </boundaryPoint>)
(<boundaryPoint> X-0.997 Y-2.999 Z2.95 </boundaryPoint>)
(<boundaryPoint> X-0.997 Y-1.096 Z2.95 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-1.096 Z2.95 </boundaryPoint>)
(<edge> outer )
G1 X-1.9 Y2.87 Z2.95 F4800.0
G1 X-1.89 Y-2.87 Z2.95 F4800.0
G1 X-1.96 Y-2.8 Z2.95 F4800.0
G1 F1200.0
G1 E26.307
G1 F4800.0
M101
M321
G1 X-1.2 Y-2.8 Z2.95 F306.32 E26.342
G1 X-1.2 Y-1.3 Z2.95 F306.32 E26.412
G1 X-2.1 Y-1.3 Z2.95 F306.32 E26.453
G1 X-2.1 Y-2.8 Z2.95 F306.32 E26.523
G1 X-1.96 Y-2.8 Z2.95 F306.32 E26.529
G1 F1200.0
G1 E26.529
G1 F306.32
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-2.799 Z2.95 </infillPoint>)
(<infillPoint> X-1.197 Y-2.799 Z2.95 </infillPoint>)
(<infillPoint> X-1.197 Y-1.296 Z2.95 </infillPoint>)
(<infillPoint> X-2.1 Y-1.296 Z2.95 </infillPoint>)
(</infillBoundary>)
G1 X-1.82 Y-1.82 Z2.95 F4800.0
G1 F1200.0
G1 E26.529
G1 F4800.0
M101
G1 X-1.64 Y-1.64 Z2.95 F306.32 E26.541
G1 X-1.48 Y-2.04 Z2.95 F306.32 E26.561
G1 X-1.77 Y-2.34 Z2.95 F306.32 E26.58
G1 F1200.0
G1 E26.58
G1 F306.32
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.997 Y-2.999 Z2.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z2.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-1.096 Z2.95 </boundaryPoint>)
(<boundaryPoint> X0.997 Y-1.096 Z2.95 </boundaryPoint>)
(<edge> outer )
G1 X-2.2 Y-2.47 Z2.95 F4800.0
G1 X2.2 Y-2.47 Z2.95 F4800.0
G1 X1.2 Y-2.48 Z2.95 F4800.0
G1 F1200.0
G1 E26.58
G1 F4800.0
M101
M321
G1 X1.2 Y-2.8 Z2.95 F306.32 E26.595
G1 X2.1 Y-2.8 Z2.95 F306.32 E26.637
G1 X2.1 Y-1.3 Z2.95 F306.32 E26.706
G1 X1.2 Y-1.3 Z2.95 F306.32 E26.748
G1 X1.2 Y-2.34 Z2.95 F306.32 E26.796
G1 X1.2 Y-2.48 Z2.95 F306.32 E26.803
G1 F1200.0
G1 E26.803
G1 F306.32
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X1.197 Y-2.799 Z2.95 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z2.95 </infillPoint>)
(<infillPoint> X2.1 Y-1.296 Z2.95 </infillPoint>)
(<infillPoint> X1.197 Y-1.296 Z2.95 </infillPoint>)
(</infillBoundary>)
G1 X1.48 Y-1.92 Z2.95 F4800.0
G1 F1200.0
G1 E26.803
G1 F4800.0
M101
G1 X1.71 Y-1.69 Z2.95 F306.32 E26.818
G1 X1.82 Y-2.14 Z2.95 F306.32 E26.839
G1 X1.57 Y-2.39 Z2.95 F306.32 E26.855
G1 F1200.0
G1 E26.855
G1 F306.32
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X2.3 Y1.098 Z2.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z2.95 </boundaryPoint>)
(<boundaryPoint> X0.997 Y2.999 Z2.95 </boundaryPoint>)
(<boundaryPoint> X0.997 Y1.098 Z2.95 </boundaryPoint>)
(<edge> outer )
G1 X1.7 Y-2.9 Z2.95 F4800.0
G1 X1.7 Y2.9 Z2.95 F4800.0
G1 X1.71 Y1.3 Z2.95 F4800.0
G1 F1200.0
G1 E26.855
G1 F4800.0
M101
M321
G1 X2.1 Y1.3 Z2.95 F306.32 E26.873
G1 X2.1 Y2.8 Z2.95 F306.32 E26.942
G1 X1.2 Y2.8 Z2.95 F306.32 E26.984
G1 X1.2 Y1.3 Z2.95 F306.32 E27.053
G1 X1.57 Y1.3 Z2.95 F306.32 E27.071
G1 X1.71 Y1.3 Z2.95 F306.32 E27.077
G1 F1200.0
G1 E27.077
G1 F306.32
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X2.1 Y1.298 Z2.95 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z2.95 </infillPoint>)
(<infillPoint> X1.197 Y2.799 Z2.95 </infillPoint>)
(<infillPoint> X1.197 Y1.298 Z2.95 </infillPoint>)
(</infillBoundary>)
G1 X1.64 Y1.64 Z2.95 F4800.0
G1 F1200.0
G1 E27.077
G1 F4800.0
M101
G1 X1.82 Y1.82 Z2.95 F306.32 E27.089
G1 X1.48 Y2.04 Z2.95 F306.32 E27.108
G1 X1.77 Y2.34 Z2.95 F306.32 E27.127
G1 F1200.0
G1 E27.127
G1 F306.32
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.997 Y1.098 Z2.95 </boundaryPoint>)
(<boundaryPoint> X-0.997 Y2.999 Z2.95 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z2.95 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y1.098 Z2.95 </boundaryPoint>)
(<edge> outer )
G1 X2.2 Y2.47 Z2.95 F4800.0
G1 X-2.2 Y2.47 Z2.95 F4800.0
G1 X-1.2 Y2.48 Z2.95 F4800.0
G1 F1200.0
G1 E27.127
G1 F4800.0
M101
M321
G1 X-1.2 Y2.8 Z2.95 F306.32 E27.142
G1 X-2.1 Y2.8 Z2.95 F306.32 E27.184
G1 X-2.1 Y1.3 Z2.95 F306.32 E27.253
G1 X-1.2 Y1.3 Z2.95 F306.32 E27.295
G1 X-1.2 Y2.34 Z2.95 F306.32 E27.343
G1 X-1.2 Y2.48 Z2.95 F306.32 E27.349
G1 F1200.0
G1 E27.349
G1 F306.32
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-1.197 Y1.298 Z2.95 </infillPoint>)
(<infillPoint> X-1.197 Y2.799 Z2.95 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z2.95 </infillPoint>)
(<infillPoint> X-2.1 Y1.298 Z2.95 </infillPoint>)
(</infillBoundary>)
G1 X-1.48 Y1.92 Z2.95 F4800.0
G1 F1200.0
G1 E27.349
G1 F4800.0
M101
G1 X-1.7 Y1.69 Z2.95 F306.32 E27.364
G1 X-1.82 Y2.14 Z2.95 F306.32 E27.386
G1 X-1.57 Y2.39 Z2.95 F306.32 E27.402
G1 F1200.0
G1 E27.402
G1 F306.32
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R5.343
(</layer>)
M73 P65 (display progress)
(<layer> 3.2 )
(<rotation> (-0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-2.999 Z3.2 </boundaryPoint>)
(<boundaryPoint> X-0.959 Y-2.999 Z3.2 </boundaryPoint>)
(<boundaryPoint> X-0.958 Y-1.064 Z3.2 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-1.064 Z3.2 </boundaryPoint>)
(<edge> outer )
G1 X-1.88 Y2.9 Z3.2 F4800.0
G1 X-1.88 Y-2.9 Z3.2 F4800.0
G1 X-2.1 Y-2.63 Z3.2 F4800.0
G1 F1200.0
G1 E27.402
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z3.2 F320.563 E27.409
G1 X-1.16 Y-2.8 Z3.2 F320.563 E27.453
G1 X-1.16 Y-1.26 Z3.2 F320.563 E27.524
G1 X-2.1 Y-1.26 Z3.2 F320.563 E27.567
G1 X-2.1 Y-2.63 Z3.2 F320.563 E27.631
G1 F1200.0
G1 E27.631
G1 F320.563
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-2.799 Z3.2 </infillPoint>)
(<infillPoint> X-1.159 Y-2.799 Z3.2 </infillPoint>)
(<infillPoint> X-1.158 Y-1.264 Z3.2 </infillPoint>)
(<infillPoint> X-2.1 Y-1.264 Z3.2 </infillPoint>)
(</infillBoundary>)
G1 X-1.44 Y-1.96 Z3.2 F4800.0
G1 F1200.0
G1 E27.631
G1 F4800.0
M101
G1 X-1.72 Y-1.67 Z3.2 F320.563 E27.649
G1 X-1.82 Y-2.14 Z3.2 F320.563 E27.671
G1 X-1.55 Y-2.41 Z3.2 F320.563 E27.688
G1 F1200.0
G1 E27.688
G1 F320.563
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.959 Y-1.064 Z3.2 </boundaryPoint>)
(<boundaryPoint> X0.959 Y-2.999 Z3.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z3.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-1.064 Z3.2 </boundaryPoint>)
(<edge> outer )
G1 X-2.16 Y-2.25 Z3.2 F4800.0
G1 X2.16 Y-2.25 Z3.2 F4800.0
G1 X1.16 Y-2.24 Z3.2 F4800.0
G1 F1200.0
G1 E27.688
G1 F4800.0
M101
M321
G1 X1.16 Y-2.41 Z3.2 F320.563 E27.696
G1 X1.16 Y-2.8 Z3.2 F320.563 E27.714
G1 X2.1 Y-2.8 Z3.2 F320.563 E27.758
G1 X2.1 Y-1.26 Z3.2 F320.563 E27.829
G1 X1.16 Y-1.26 Z3.2 F320.563 E27.872
G1 X1.16 Y-2.24 Z3.2 F320.563 E27.917
G1 F1200.0
G1 E27.917
G1 F320.563
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X1.159 Y-1.264 Z3.2 </infillPoint>)
(<infillPoint> X1.159 Y-2.799 Z3.2 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z3.2 </infillPoint>)
(<infillPoint> X2.1 Y-1.264 Z3.2 </infillPoint>)
(</infillBoundary>)
G1 X1.82 Y-1.82 Z3.2 F4800.0
G1 F1200.0
G1 E27.917
G1 F4800.0
M101
G1 X1.6 Y-1.6 Z3.2 F320.563 E27.931
G1 X1.44 Y-2.0 Z3.2 F320.563 E27.951
G1 X1.77 Y-2.34 Z3.2 F320.563 E27.973
G1 F1200.0
G1 E27.973
G1 F320.563
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X2.3 Y1.064 Z3.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z3.2 </boundaryPoint>)
(<boundaryPoint> X0.959 Y2.999 Z3.2 </boundaryPoint>)
(<boundaryPoint> X0.959 Y1.064 Z3.2 </boundaryPoint>)
(<edge> outer )
G1 X1.61 Y-2.86 Z3.2 F4800.0
G1 X1.61 Y2.86 Z3.2 F4800.0
G1 X1.61 Y1.26 Z3.2 F4800.0
G1 F1200.0
G1 E27.973
G1 F4800.0
M101
M321
G1 X1.77 Y1.26 Z3.2 F320.563 E27.981
G1 X2.1 Y1.26 Z3.2 F320.563 E27.996
G1 X2.1 Y2.8 Z3.2 F320.563 E28.067
G1 X1.16 Y2.8 Z3.2 F320.563 E28.11
G1 X1.16 Y1.26 Z3.2 F320.563 E28.181
G1 X1.61 Y1.26 Z3.2 F320.563 E28.202
G1 F1200.0
G1 E28.202
G1 F320.563
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X2.1 Y1.264 Z3.2 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z3.2 </infillPoint>)
(<infillPoint> X1.159 Y2.799 Z3.2 </infillPoint>)
(<infillPoint> X1.159 Y1.264 Z3.2 </infillPoint>)
(</infillBoundary>)
G1 X1.44 Y1.96 Z3.2 F4800.0
G1 F1200.0
G1 E28.202
G1 F4800.0
M101
G1 X1.72 Y1.67 Z3.2 F320.563 E28.22
G1 X1.82 Y2.14 Z3.2 F320.563 E28.242
G1 X1.55 Y2.41 Z3.2 F320.563 E28.26
G1 F1200.0
G1 E28.26
G1 F320.563
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-0.958 Y1.064 Z3.2 </boundaryPoint>)
(<boundaryPoint> X-0.959 Y2.999 Z3.2 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z3.2 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y1.064 Z3.2 </boundaryPoint>)
(<edge> outer )
G1 X2.16 Y2.25 Z3.2 F4800.0
G1 X-2.16 Y2.25 Z3.2 F4800.0
G1 X-1.16 Y2.24 Z3.2 F4800.0
G1 F1200.0
G1 E28.26
G1 F4800.0
M101
M321
G1 X-1.16 Y2.4 Z3.2 F320.563 E28.267
G1 X-1.16 Y2.8 Z3.2 F320.563 E28.286
G1 X-2.1 Y2.8 Z3.2 F320.563 E28.329
G1 X-2.1 Y1.26 Z3.2 F320.563 E28.4
G1 X-1.16 Y1.26 Z3.2 F320.563 E28.444
G1 X-1.16 Y2.24 Z3.2 F320.563 E28.488
G1 F1200.0
G1 E28.488
G1 F320.563
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-1.158 Y1.264 Z3.2 </infillPoint>)
(<infillPoint> X-1.159 Y2.799 Z3.2 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z3.2 </infillPoint>)
(<infillPoint> X-2.1 Y1.264 Z3.2 </infillPoint>)
(</infillBoundary>)
G1 X-1.6 Y1.6 Z3.2 F4800.0
G1 F1200.0
G1 E28.488
G1 F4800.0
M101
G1 X-1.82 Y1.82 Z3.2 F320.563 E28.503
G1 X-1.44 Y2.0 Z3.2 F320.563 E28.522
G1 X-1.77 Y2.34 Z3.2 F320.563 E28.544
G1 F1200.0
G1 E28.544
G1 F320.563
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R6.008
(</layer>)
M73 P72 (display progress)
(<layer> 3.45 )
(<rotation> (0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-2.999 Z3.45 </boundaryPoint>)
(<boundaryPoint> X-0.847 Y-2.999 Z3.45 </boundaryPoint>)
(<boundaryPoint> X-0.847 Y-0.963 Z3.45 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-0.963 Z3.45 </boundaryPoint>)
(<edge> outer )
G1 X-1.84 Y2.86 Z3.45 F4800.0
G1 X-1.84 Y-2.86 Z3.45 F4800.0
G1 X-2.1 Y-2.33 Z3.45 F4800.0
G1 F1200.0
G1 E28.544
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z3.45 F360.502 E28.566
G1 X-1.05 Y-2.8 Z3.45 F360.502 E28.614
G1 X-1.05 Y-1.16 Z3.45 F360.502 E28.69
G1 X-2.1 Y-1.16 Z3.45 F360.502 E28.739
G1 X-2.1 Y-2.33 Z3.45 F360.502 E28.792
G1 F1200.0
G1 E28.792
G1 F360.502
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-2.799 Z3.45 </infillPoint>)
(<infillPoint> X-1.047 Y-2.799 Z3.45 </infillPoint>)
(<infillPoint> X-1.047 Y-1.163 Z3.45 </infillPoint>)
(<infillPoint> X-2.1 Y-1.163 Z3.45 </infillPoint>)
(</infillBoundary>)
G1 X-1.82 Y-1.82 Z3.45 F4800.0
G1 F1200.0
G1 E28.792
G1 F4800.0
M101
G1 X-1.5 Y-1.5 Z3.45 F360.502 E28.813
G1 X-1.33 Y-1.89 Z3.45 F360.502 E28.833
G1 X-1.77 Y-2.34 Z3.45 F360.502 E28.862
G1 F1200.0
G1 E28.862
G1 F360.502
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.847 Y-0.963 Z3.45 </boundaryPoint>)
(<boundaryPoint> X0.847 Y-2.999 Z3.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z3.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-0.963 Z3.45 </boundaryPoint>)
(<edge> outer )
G1 X-2.25 Y-1.9 Z3.45 F4800.0
G1 X2.25 Y-1.9 Z3.45 F4800.0
G1 X1.05 Y-1.87 Z3.45 F4800.0
G1 F1200.0
G1 E28.862
G1 F4800.0
M101
M321
G1 X1.05 Y-2.34 Z3.45 F360.502 E28.884
G1 X1.05 Y-2.8 Z3.45 F360.502 E28.905
G1 X2.1 Y-2.8 Z3.45 F360.502 E28.954
G1 X2.1 Y-1.16 Z3.45 F360.502 E29.03
G1 X1.05 Y-1.16 Z3.45 F360.502 E29.078
G1 X1.05 Y-1.87 Z3.45 F360.502 E29.111
G1 F1200.0
G1 E29.111
G1 F360.502
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X1.047 Y-1.163 Z3.45 </infillPoint>)
(<infillPoint> X1.047 Y-2.799 Z3.45 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z3.45 </infillPoint>)
(<infillPoint> X2.1 Y-1.163 Z3.45 </infillPoint>)
(</infillBoundary>)
G1 X1.33 Y-2.07 Z3.45 F4800.0
G1 F1200.0
G1 E29.111
G1 F4800.0
M101
G1 X1.77 Y-1.62 Z3.45 F360.502 E29.14
G1 X1.82 Y-2.14 Z3.45 F360.502 E29.164
G1 X1.5 Y-2.46 Z3.45 F360.502 E29.185
G1 F1200.0
G1 E29.185
G1 F360.502
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X2.3 Y2.999 Z3.45 </boundaryPoint>)
(<boundaryPoint> X0.847 Y2.999 Z3.45 </boundaryPoint>)
(<boundaryPoint> X0.847 Y0.963 Z3.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y0.963 Z3.45 </boundaryPoint>)
(<edge> outer )
G1 X1.36 Y-2.96 Z3.45 F4800.0
G1 X1.36 Y2.96 Z3.45 F4800.0
G1 X1.05 Y1.18 Z3.45 F4800.0
G1 F1200.0
G1 E29.185
G1 F4800.0
M101
M321
G1 X1.05 Y1.16 Z3.45 F360.502 E29.186
G1 X1.5 Y1.16 Z3.45 F360.502 E29.207
G1 X2.1 Y1.16 Z3.45 F360.502 E29.234
G1 X2.1 Y2.8 Z3.45 F360.502 E29.31
G1 X1.05 Y2.8 Z3.45 F360.502 E29.359
G1 X1.05 Y1.18 Z3.45 F360.502 E29.433
G1 F1200.0
G1 E29.433
G1 F360.502
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X2.1 Y2.799 Z3.45 </infillPoint>)
(<infillPoint> X1.047 Y2.799 Z3.45 </infillPoint>)
(<infillPoint> X1.047 Y1.163 Z3.45 </infillPoint>)
(<infillPoint> X2.1 Y1.163 Z3.45 </infillPoint>)
(</infillBoundary>)
G1 X1.5 Y1.5 Z3.45 F4800.0
G1 F1200.0
G1 E29.433
G1 F4800.0
M101
G1 X1.82 Y1.82 Z3.45 F360.502 E29.454
G1 X1.33 Y1.89 Z3.45 F360.502 E29.477
G1 X1.77 Y2.34 Z3.45 F360.502 E29.506
G1 F1200.0
G1 E29.506
G1 F360.502
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y0.963 Z3.45 </boundaryPoint>)
(<boundaryPoint> X-0.847 Y0.963 Z3.45 </boundaryPoint>)
(<boundaryPoint> X-0.847 Y2.999 Z3.45 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y2.999 Z3.45 </boundaryPoint>)
(<edge> outer )
G1 X2.25 Y1.9 Z3.45 F4800.0
G1 X-2.25 Y1.9 Z3.45 F4800.0
G1 X-1.05 Y1.87 Z3.45 F4800.0
G1 F1200.0
G1 E29.506
G1 F4800.0
M101
M321
G1 X-1.05 Y2.34 Z3.45 F360.502 E29.528
G1 X-1.05 Y2.8 Z3.45 F360.502 E29.549
G1 X-2.1 Y2.8 Z3.45 F360.502 E29.598
G1 X-2.1 Y1.16 Z3.45 F360.502 E29.674
G1 X-1.05 Y1.16 Z3.45 F360.502 E29.722
G1 X-1.05 Y1.87 Z3.45 F360.502 E29.755
G1 F1200.0
G1 E29.755
G1 F360.502
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y1.163 Z3.45 </infillPoint>)
(<infillPoint> X-1.047 Y1.163 Z3.45 </infillPoint>)
(<infillPoint> X-1.047 Y2.799 Z3.45 </infillPoint>)
(<infillPoint> X-2.1 Y2.799 Z3.45 </infillPoint>)
(</infillBoundary>)
G1 X-1.33 Y2.07 Z3.45 F4800.0
G1 F1200.0
G1 E29.755
G1 F4800.0
M101
G1 X-1.77 Y1.62 Z3.45 F360.502 E29.784
G1 X-1.82 Y2.14 Z3.45 F360.502 E29.808
G1 X-1.5 Y2.46 Z3.45 F360.502 E29.829
G1 F1200.0
G1 E29.829
G1 F360.502
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R8.055
(</layer>)
M73 P79 (display progress)
(<layer> 3.7 )
(<rotation> (-0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-2.999 Z3.7 </boundaryPoint>)
(<boundaryPoint> X-0.617 Y-2.999 Z3.7 </boundaryPoint>)
(<boundaryPoint> X-0.618 Y-0.779 Z3.7 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-0.779 Z3.7 </boundaryPoint>)
(<edge> outer )
G1 X-1.88 Y2.96 Z3.7 F4800.0
G1 X-1.88 Y-2.96 Z3.7 F4800.0
G1 X-2.08 Y-2.8 Z3.7 F4800.0
G1 F1200.0
G1 E29.829
G1 F4800.0
M101
M321
G1 X-0.82 Y-2.8 Z3.7 F483.309 E29.887
G1 X-0.82 Y-0.98 Z3.7 F483.309 E29.971
G1 X-2.1 Y-0.98 Z3.7 F483.309 E30.03
G1 X-2.1 Y-2.8 Z3.7 F483.309 E30.114
G1 X-2.08 Y-2.8 Z3.7 F483.309 E30.115
G1 F1200.0
G1 E30.115
G1 F483.309
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-2.799 Z3.7 </infillPoint>)
(<infillPoint> X-0.817 Y-2.799 Z3.7 </infillPoint>)
(<infillPoint> X-0.818 Y-0.979 Z3.7 </infillPoint>)
(<infillPoint> X-2.1 Y-0.979 Z3.7 </infillPoint>)
(</infillBoundary>)
G1 X-1.1 Y-1.73 Z3.7 F4800.0
G1 F1200.0
G1 E30.115
G1 F4800.0
M101
G1 X-1.57 Y-1.26 Z3.7 F483.309 E30.146
G1 X-1.82 Y-1.57 Z3.7 F483.309 E30.165
G1 X-1.1 Y-2.29 Z3.7 F483.309 E30.212
G1 X-1.44 Y-2.52 Z3.7 F483.309 E30.231
G1 X-1.82 Y-2.14 Z3.7 F483.309 E30.255
G1 F1200.0
G1 E30.255
G1 F483.309
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X2.3 Y-2.999 Z3.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-0.779 Z3.7 </boundaryPoint>)
(<boundaryPoint> X0.62 Y-0.779 Z3.7 </boundaryPoint>)
(<boundaryPoint> X0.618 Y-2.999 Z3.7 </boundaryPoint>)
(<edge> outer )
G1 X-2.22 Y-2.16 Z3.7 F4800.0
G1 X2.22 Y-2.17 Z3.7 F4800.0
G1 X0.82 Y-2.17 Z3.7 F4800.0
G1 F1200.0
G1 E30.255
G1 F4800.0
M101
M321
G1 X0.82 Y-2.8 Z3.7 F483.309 E30.285
G1 X2.1 Y-2.8 Z3.7 F483.309 E30.344
G1 X2.1 Y-0.98 Z3.7 F483.309 E30.428
G1 X0.82 Y-0.98 Z3.7 F483.309 E30.487
G1 X0.82 Y-2.14 Z3.7 F483.309 E30.541
G1 X0.82 Y-2.17 Z3.7 F483.309 E30.542
G1 F1200.0
G1 E30.542
G1 F483.309
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X2.1 Y-2.799 Z3.7 </infillPoint>)
(<infillPoint> X2.1 Y-0.979 Z3.7 </infillPoint>)
(<infillPoint> X0.82 Y-0.979 Z3.7 </infillPoint>)
(<infillPoint> X0.818 Y-2.799 Z3.7 </infillPoint>)
(</infillBoundary>)
G1 X1.82 Y-1.82 Z3.7 F4800.0
G1 F1200.0
G1 E30.542
G1 F4800.0
M101
G1 X1.29 Y-1.29 Z3.7 F483.309 E30.576
G1 X1.1 Y-1.67 Z3.7 F483.309 E30.596
G1 X1.77 Y-2.34 Z3.7 F483.309 E30.64
G1 X1.39 Y-2.52 Z3.7 F483.309 E30.659
G1 X1.1 Y-2.23 Z3.7 F483.309 E30.678
G1 F1200.0
G1 E30.678
G1 F483.309
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X0.618 Y2.999 Z3.7 </boundaryPoint>)
(<boundaryPoint> X0.62 Y0.779 Z3.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y0.779 Z3.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z3.7 </boundaryPoint>)
(<edge> outer )
G1 X1.12 Y-2.98 Z3.7 F4800.0
G1 X1.12 Y2.98 Z3.7 F4800.0
G1 X1.12 Y0.98 Z3.7 F4800.0
G1 F1200.0
G1 E30.678
G1 F4800.0
M101
M321
G1 X2.1 Y0.98 Z3.7 F483.309 E30.724
G1 X2.1 Y2.8 Z3.7 F483.309 E30.808
G1 X0.82 Y2.8 Z3.7 F483.309 E30.867
G1 X0.82 Y0.98 Z3.7 F483.309 E30.951
G1 X1.1 Y0.98 Z3.7 F483.309 E30.964
G1 X1.12 Y0.98 Z3.7 F483.309 E30.965
G1 F1200.0
G1 E30.965
G1 F483.309
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X0.818 Y2.799 Z3.7 </infillPoint>)
(<infillPoint> X0.82 Y0.979 Z3.7 </infillPoint>)
(<infillPoint> X2.1 Y0.979 Z3.7 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z3.7 </infillPoint>)
(</infillBoundary>)
G1 X1.1 Y1.73 Z3.7 F4800.0
G1 F1200.0
G1 E30.965
G1 F4800.0
M101
G1 X1.57 Y1.26 Z3.7 F483.309 E30.996
G1 X1.82 Y1.57 Z3.7 F483.309 E31.014
G1 X1.1 Y2.29 Z3.7 F483.309 E31.061
G1 X1.44 Y2.52 Z3.7 F483.309 E31.08
G1 X1.82 Y2.14 Z3.7 F483.309 E31.105
G1 F1200.0
G1 E31.105
G1 F483.309
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y2.999 Z3.7 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y0.779 Z3.7 </boundaryPoint>)
(<boundaryPoint> X-0.618 Y0.779 Z3.7 </boundaryPoint>)
(<boundaryPoint> X-0.617 Y2.999 Z3.7 </boundaryPoint>)
(<edge> outer )
G1 X2.22 Y2.16 Z3.7 F4800.0
G1 X-2.22 Y2.17 Z3.7 F4800.0
G1 X-0.82 Y2.16 Z3.7 F4800.0
G1 F1200.0
G1 E31.105
G1 F4800.0
M101
M321
G1 X-0.82 Y2.8 Z3.7 F483.309 E31.134
G1 X-2.1 Y2.8 Z3.7 F483.309 E31.193
G1 X-2.1 Y0.98 Z3.7 F483.309 E31.277
G1 X-0.82 Y0.98 Z3.7 F483.309 E31.337
G1 X-0.82 Y2.14 Z3.7 F483.309 E31.39
G1 X-0.82 Y2.16 Z3.7 F483.309 E31.391
G1 F1200.0
G1 E31.391
G1 F483.309
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y2.799 Z3.7 </infillPoint>)
(<infillPoint> X-2.1 Y0.979 Z3.7 </infillPoint>)
(<infillPoint> X-0.818 Y0.979 Z3.7 </infillPoint>)
(<infillPoint> X-0.817 Y2.799 Z3.7 </infillPoint>)
(</infillBoundary>)
G1 X-1.29 Y1.29 Z3.7 F4800.0
G1 F1200.0
G1 E31.391
G1 F4800.0
M101
G1 X-1.82 Y1.82 Z3.7 F483.309 E31.426
G1 X-1.77 Y2.34 Z3.7 F483.309 E31.45
G1 X-1.1 Y1.66 Z3.7 F483.309 E31.494
G1 X-1.1 Y2.23 Z3.7 F483.309 E31.52
G1 X-1.39 Y2.52 Z3.7 F483.309 E31.539
G1 F1200.0
G1 E31.539
G1 F483.309
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R13.48
(</layer>)
M73 P86 (display progress)
(<layer> 3.95 )
(<rotation> (0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y-0.374 Z3.95 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-2.999 Z3.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z3.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-0.374 Z3.95 </boundaryPoint>)
(<edge> outer )
G1 X-1.85 Y2.98 Z3.95 F4800.0
G1 X-1.85 Y-2.98 Z3.95 F4800.0
G1 X-2.1 Y-2.52 Z3.95 F4800.0
G1 F1200.0
G1 E31.539
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z3.95 F808.682 E31.552
G1 X2.1 Y-2.8 Z3.95 F808.682 E31.746
G1 X2.1 Y-0.57 Z3.95 F808.682 E31.849
G1 X-2.1 Y-0.57 Z3.95 F808.682 E32.043
G1 X-2.1 Y-2.52 Z3.95 F808.682 E32.133
G1 F1200.0
G1 E32.133
G1 F808.682
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y-0.574 Z3.95 </infillPoint>)
(<infillPoint> X-2.1 Y-2.799 Z3.95 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z3.95 </infillPoint>)
(<infillPoint> X2.1 Y-0.574 Z3.95 </infillPoint>)
(</infillBoundary>)
G1 X-1.82 Y-1.25 Z3.95 F4800.0
G1 F1200.0
G1 E32.133
G1 F4800.0
M101
G1 X-1.42 Y-0.85 Z3.95 F808.682 E32.159
G1 X-0.85 Y-0.85 Z3.95 F808.682 E32.185
G1 X-1.82 Y-1.82 Z3.95 F808.682 E32.248
G1 X-1.77 Y-2.34 Z3.95 F808.682 E32.272
G1 X-0.29 Y-0.85 Z3.95 F808.682 E32.369
G1 X0.28 Y-0.85 Z3.95 F808.682 E32.395
G1 X-1.39 Y-2.52 Z3.95 F808.682 E32.504
G1 X-0.82 Y-2.52 Z3.95 F808.682 E32.53
G1 X0.84 Y-0.85 Z3.95 F808.682 E32.639
G1 X1.41 Y-0.85 Z3.95 F808.682 E32.665
G1 X-0.26 Y-2.52 Z3.95 F808.682 E32.774
G1 X0.31 Y-2.52 Z3.95 F808.682 E32.8
G1 X1.78 Y-1.04 Z3.95 F808.682 E32.896
G1 X1.82 Y-1.57 Z3.95 F808.682 E32.921
G1 X0.88 Y-2.52 Z3.95 F808.682 E32.983
G1 X1.44 Y-2.52 Z3.95 F808.682 E33.009
G1 X1.82 Y-2.14 Z3.95 F808.682 E33.034
G1 F1200.0
G1 E33.034
G1 F808.682
M103
(</infill>)
(</nestedRing>)
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y2.999 Z3.95 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y0.374 Z3.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y0.374 Z3.95 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z3.95 </boundaryPoint>)
(<edge> outer )
G1 X1.56 Y-2.77 Z3.95 F4800.0
G1 X1.56 Y2.77 Z3.95 F4800.0
G1 X1.54 Y0.57 Z3.95 F4800.0
G1 F1200.0
G1 E33.034
G1 F4800.0
M101
M321
G1 X1.82 Y0.57 Z3.95 F808.682 E33.047
G1 X2.1 Y0.57 Z3.95 F808.682 E33.06
G1 X2.1 Y2.8 Z3.95 F808.682 E33.162
G1 X-2.1 Y2.8 Z3.95 F808.682 E33.356
G1 X-2.1 Y0.57 Z3.95 F808.682 E33.459
G1 X1.54 Y0.57 Z3.95 F808.682 E33.627
G1 F1200.0
G1 E33.627
G1 F808.682
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y2.799 Z3.95 </infillPoint>)
(<infillPoint> X-2.1 Y0.574 Z3.95 </infillPoint>)
(<infillPoint> X2.1 Y0.574 Z3.95 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z3.95 </infillPoint>)
(</infillBoundary>)
G1 X1.42 Y0.85 Z3.95 F4800.0
G1 F1200.0
G1 E33.627
G1 F4800.0
M101
G1 X1.82 Y1.25 Z3.95 F808.682 E33.653
G1 X1.82 Y1.82 Z3.95 F808.682 E33.68
G1 X0.85 Y0.85 Z3.95 F808.682 E33.743
G1 X0.29 Y0.85 Z3.95 F808.682 E33.769
G1 X1.77 Y2.34 Z3.95 F808.682 E33.866
G1 X1.39 Y2.52 Z3.95 F808.682 E33.885
G1 X-0.28 Y0.85 Z3.95 F808.682 E33.994
G1 X-0.84 Y0.85 Z3.95 F808.682 E34.02
G1 X0.82 Y2.52 Z3.95 F808.682 E34.129
G1 X0.26 Y2.52 Z3.95 F808.682 E34.155
G1 X-1.41 Y0.85 Z3.95 F808.682 E34.264
G1 X-1.78 Y1.04 Z3.95 F808.682 E34.284
G1 X-0.31 Y2.52 Z3.95 F808.682 E34.38
G1 X-0.88 Y2.52 Z3.95 F808.682 E34.406
G1 X-1.82 Y1.57 Z3.95 F808.682 E34.468
G1 X-1.82 Y2.14 Z3.95 F808.682 E34.494
G1 X-1.44 Y2.52 Z3.95 F808.682 E34.519
G1 F1200.0
G1 E34.519
G1 F808.682
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R15.01
(</layer>)
M73 P90 (display progress)
(<layer> 4.2 )
(<rotation> (-0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y2.999 Z4.2 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-2.999 Z4.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z4.2 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z4.2 </boundaryPoint>)
(<edge> outer )
G1 X-1.69 Y2.77 Z4.2 F4800.0
G1 X-1.69 Y-2.77 Z4.2 F4800.0
G1 X-1.89 Y-2.8 Z4.2 F4800.0
G1 F1200.0
G1 E34.519
G1 F4800.0
M101
M321
G1 X2.1 Y-2.8 Z4.2 F900.688 E34.703
G1 X2.1 Y2.8 Z4.2 F900.688 E34.961
G1 X-2.1 Y2.8 Z4.2 F900.688 E35.155
G1 X-2.1 Y-2.8 Z4.2 F900.688 E35.414
G1 X-1.89 Y-2.8 Z4.2 F900.688 E35.424
G1 F1200.0
G1 E35.424
G1 F900.688
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y2.799 Z4.2 </infillPoint>)
(<infillPoint> X-2.1 Y-2.799 Z4.2 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z4.2 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z4.2 </infillPoint>)
(</infillBoundary>)
G1 X-1.82 Y1.25 Z4.2 F4800.0
G1 F1200.0
G1 E35.424
G1 F4800.0
M101
G1 X1.77 Y-2.34 Z4.2 F900.688 E35.658
G1 X1.39 Y-2.52 Z4.2 F900.688 E35.678
G1 X-1.82 Y0.69 Z4.2 F900.688 E35.888
G1 X-1.82 Y0.12 Z4.2 F900.688 E35.914
G1 X0.82 Y-2.52 Z4.2 F900.688 E36.086
G1 X0.26 Y-2.52 Z4.2 F900.688 E36.113
G1 X-1.82 Y-0.44 Z4.2 F900.688 E36.248
G1 X-1.82 Y-1.01 Z4.2 F900.688 E36.274
G1 X-0.31 Y-2.52 Z4.2 F900.688 E36.373
G1 X-0.88 Y-2.52 Z4.2 F900.688 E36.399
G1 X-1.82 Y-1.57 Z4.2 F900.688 E36.461
G1 X-1.82 Y-2.14 Z4.2 F900.688 E36.487
G1 X-1.44 Y-2.52 Z4.2 F900.688 E36.512
G1 F1200.0
G1 E36.512
G1 F900.688
M103
G1 X1.82 Y-1.82 Z4.2 F4800.0
G1 F1200.0
G1 E36.512
G1 F4800.0
M101
G1 X-1.82 Y1.82 Z4.2 F900.688 E36.749
G1 X-1.77 Y2.34 Z4.2 F900.688 E36.773
G1 X1.82 Y-1.25 Z4.2 F900.688 E37.008
G1 X1.82 Y-0.69 Z4.2 F900.688 E37.034
G1 X-1.39 Y2.52 Z4.2 F900.688 E37.244
G1 X-0.82 Y2.52 Z4.2 F900.688 E37.27
G1 X1.82 Y-0.12 Z4.2 F900.688 E37.443
G1 X1.82 Y0.44 Z4.2 F900.688 E37.469
G1 X-0.26 Y2.52 Z4.2 F900.688 E37.604
G1 X0.31 Y2.52 Z4.2 F900.688 E37.63
G1 X1.82 Y1.01 Z4.2 F900.688 E37.729
G1 X1.82 Y1.57 Z4.2 F900.688 E37.755
G1 X0.88 Y2.52 Z4.2 F900.688 E37.817
G1 X1.44 Y2.52 Z4.2 F900.688 E37.843
G1 X1.82 Y2.14 Z4.2 F900.688 E37.868
G1 F1200.0
G1 E37.868
G1 F900.688
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R14.91
(</layer>)
M73 P93 (display progress)
(<layer> 4.45 )
(<rotation> (0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y2.999 Z4.45 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-2.999 Z4.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z4.45 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z4.45 </boundaryPoint>)
(<edge> outer )
G1 X-2.1 Y-2.7 Z4.45 F4800.0
G1 F1200.0
G1 E37.868
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z4.45 F894.519 E37.872
G1 X2.1 Y-2.8 Z4.45 F894.519 E38.066
G1 X2.1 Y2.8 Z4.45 F894.519 E38.325
G1 X-2.1 Y2.8 Z4.45 F894.519 E38.519
G1 X-2.1 Y-2.7 Z4.45 F894.519 E38.773
G1 F1200.0
G1 E38.773
G1 F894.519
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y2.799 Z4.45 </infillPoint>)
(<infillPoint> X-2.1 Y-2.799 Z4.45 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z4.45 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z4.45 </infillPoint>)
(</infillBoundary>)
G1 X-1.82 Y-1.82 Z4.45 F4800.0
G1 F1200.0
G1 E38.773
G1 F4800.0
M101
G1 X1.82 Y1.82 Z4.45 F894.519 E39.011
G1 X1.77 Y2.34 Z4.45 F894.519 E39.035
G1 X-1.82 Y-1.25 Z4.45 F894.519 E39.27
G1 X-1.82 Y-0.69 Z4.45 F894.519 E39.296
G1 X1.39 Y2.52 Z4.45 F894.519 E39.505
G1 X0.82 Y2.52 Z4.45 F894.519 E39.532
G1 X-1.82 Y-0.12 Z4.45 F894.519 E39.704
G1 X-1.82 Y0.44 Z4.45 F894.519 E39.73
G1 X0.26 Y2.52 Z4.45 F894.519 E39.866
G1 X-0.31 Y2.52 Z4.45 F894.519 E39.892
G1 X-1.82 Y1.01 Z4.45 F894.519 E39.991
G1 X-1.82 Y1.57 Z4.45 F894.519 E40.017
G1 X-0.88 Y2.52 Z4.45 F894.519 E40.079
G1 X-1.44 Y2.52 Z4.45 F894.519 E40.105
G1 X-1.82 Y2.14 Z4.45 F894.519 E40.13
G1 F1200.0
G1 E40.13
G1 F894.519
M103
G1 X1.82 Y1.25 Z4.45 F4800.0
G1 F1200.0
G1 E40.13
G1 F4800.0
M101
G1 X-1.77 Y-2.34 Z4.45 F894.519 E40.364
G1 X-1.39 Y-2.52 Z4.45 F894.519 E40.384
G1 X1.82 Y0.69 Z4.45 F894.519 E40.594
G1 X1.82 Y0.12 Z4.45 F894.519 E40.62
G1 X-0.82 Y-2.52 Z4.45 F894.519 E40.792
G1 X-0.26 Y-2.52 Z4.45 F894.519 E40.818
G1 X1.82 Y-0.44 Z4.45 F894.519 E40.954
G1 X1.82 Y-1.01 Z4.45 F894.519 E40.98
G1 X0.31 Y-2.52 Z4.45 F894.519 E41.079
G1 X0.88 Y-2.52 Z4.45 F894.519 E41.105
G1 X1.82 Y-1.57 Z4.45 F894.519 E41.167
G1 X1.82 Y-2.14 Z4.45 F894.519 E41.193
G1 X1.44 Y-2.52 Z4.45 F894.519 E41.218
G1 F1200.0
G1 E41.218
G1 F894.519
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R14.89
(</layer>)
M73 P96 (display progress)
(<layer> 4.7 )
(<rotation> (-0.707106781187+0.707106781187j) )
(<nestedRing>)
(<boundaryPerimeter>)
(<boundaryPoint> X-2.3 Y2.999 Z4.7 </boundaryPoint>)
(<boundaryPoint> X-2.3 Y-2.999 Z4.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y-2.999 Z4.7 </boundaryPoint>)
(<boundaryPoint> X2.3 Y2.999 Z4.7 </boundaryPoint>)
(<edge> outer )
G1 X-2.1 Y-2.4 Z4.7 F4800.0
G1 F1200.0
G1 E41.218
G1 F4800.0
M101
M321
G1 X-2.1 Y-2.8 Z4.7 F893.694 E41.236
G1 X2.1 Y-2.8 Z4.7 F893.694 E41.43
G1 X2.1 Y2.8 Z4.7 F893.694 E41.689
G1 X-2.1 Y2.8 Z4.7 F893.694 E41.883
G1 X-2.1 Y-2.4 Z4.7 F893.694 E42.123
G1 F1200.0
G1 E42.123
G1 F893.694
M103
M320
(</edge>)
(</boundaryPerimeter>)
(<infill>)
(<infillBoundary>)
(<infillPoint> X-2.1 Y2.799 Z4.7 </infillPoint>)
(<infillPoint> X-2.1 Y-2.799 Z4.7 </infillPoint>)
(<infillPoint> X2.1 Y-2.799 Z4.7 </infillPoint>)
(<infillPoint> X2.1 Y2.799 Z4.7 </infillPoint>)
(</infillBoundary>)
G1 X-1.82 Y1.25 Z4.7 F4800.0
G1 F1200.0
G1 E42.123
G1 F4800.0
M101
G1 X1.77 Y-2.34 Z4.7 F893.694 E42.357
G1 X1.39 Y-2.52 Z4.7 F893.694 E42.377
G1 X-1.82 Y0.69 Z4.7 F893.694 E42.586
G1 X-1.82 Y0.12 Z4.7 F893.694 E42.613
G1 X0.82 Y-2.52 Z4.7 F893.694 E42.785
G1 X0.26 Y-2.52 Z4.7 F893.694 E42.811
G1 X-1.82 Y-0.44 Z4.7 F893.694 E42.947
G1 X-1.82 Y-1.01 Z4.7 F893.694 E42.973
G1 X-0.31 Y-2.52 Z4.7 F893.694 E43.072
G1 X-0.88 Y-2.52 Z4.7 F893.694 E43.098
G1 X-1.82 Y-1.57 Z4.7 F893.694 E43.159
G1 X-1.82 Y-2.14 Z4.7 F893.694 E43.186
G1 X-1.44 Y-2.52 Z4.7 F893.694 E43.21
G1 F1200.0
G1 E43.21
G1 F893.694
M103
G1 X1.82 Y-1.82 Z4.7 F4800.0
G1 F1200.0
G1 E43.21
G1 F4800.0
M101
G1 X-1.82 Y1.82 Z4.7 F893.694 E43.448
G1 X-1.77 Y2.34 Z4.7 F893.694 E43.472
G1 X1.82 Y-1.25 Z4.7 F893.694 E43.707
G1 X1.82 Y-0.69 Z4.7 F893.694 E43.733
G1 X-1.39 Y2.52 Z4.7 F893.694 E43.942
G1 X-0.82 Y2.52 Z4.7 F893.694 E43.968
G1 X1.82 Y-0.12 Z4.7 F893.694 E44.141
G1 X1.82 Y0.44 Z4.7 F893.694 E44.167
G1 X-0.26 Y2.52 Z4.7 F893.694 E44.303
G1 X0.31 Y2.52 Z4.7 F893.694 E44.329
G1 X1.82 Y1.01 Z4.7 F893.694 E44.427
G1 X1.82 Y1.57 Z4.7 F893.694 E44.454
G1 X0.88 Y2.52 Z4.7 F893.694 E44.515
G1 X1.44 Y2.52 Z4.7 F893.694 E44.541
G1 X1.82 Y2.14 Z4.7 F893.694 E44.566
G1 F1200.0
G1 E44.566
G1 F893.694
M103
(</infill>)
(</nestedRing>)
(</rotation>)
;M108 R60.0
(</layer>)
(</crafting>)
M104 S0
;M113 S0.0
(******* End.gcode*******)
M73 P100 ( End  build progress )
G0 Z150 ( Send Z axis to bottom of machine )
M18 ( Disable steppers )
M109 S0 T0 ( Cool down the build platform )
M104 S0 T0 ( Cool down the Right Extruder )
M104 S0 T1 ( Cool down the Left Extruder )
G162 X Y F2500 ( Home XY endstops )
M18 ( Disable stepper motors )
M70 P5 ( We <3 Making Things!)
M72 P1  ( Play Ta-Da song )
(*********end End.gcode*******)
